In [198]:
%reload_ext sql

In [199]:
from sqlalchemy import create_engine

In [200]:
%sql postgresql://oceane:LunedeTerre@localhost/postgres

In [201]:
import pandas as pd

In [202]:
dataset = pd.read_csv("titanic_train.csv")

In [30]:
dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
dataset.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

Activités à réaliser :

-Modèle de donnée d'une base de donnée réel (TITANIC)
-Script creation base de données 
-Manipulation du language sql 
-Exploitation d'une base de donnée et visualisation des résultats

## PHASE 1 ##

Pour faire bien analyser les données nous nous sommes posée les questions suivantes afin de comprendre les différents liens que nous pourrions faire pour exploiter aux mieux ces données :
Quels est le profil des passagers ? Le bateau était majoritairement composé d'hommes ou de femmes  ?

Dans un premier temps, suite aux informations trouvé sur le site « kaggle », nous remarquons que les passagers étaient majoritairement des hommes. Sont-ils jeunes ou agées ?
Nous remarquons qu’il y a des personnes de tout âge confondu, des tranches d’âge
différentes tels que des enfants entre 1 et 12 ans , des adolescents entre 13 et 18 ans... 
Cependant , il y a une grande majorité d’adulte plus ou moins jeunes (ne pas hésiter à regrouper par tranche d’âge) Les personnes ayant embarqué au port de Southampton semblent être les personnes qui ont le
moins survécu (voir ligne 71 à 75 du tableau). Cette base de données Titanic nous donne toutes les informations concernant les individus qui étaient présents au moment du drame.

ANALYSE GLOBAL :

- Le fichier est composé de 12 colonnes (Attributs).
- Le fichier est composé de 891 lignes (Tuples).
- Les différentes données sont sous fichier csv donc séparées/délimités par des points virgules
- Le fichier exploite les données des personnes ayant survécu ou non au drame du Titanic

- Dans ce fichier nous retrouvons les attributs suivants : 

- Le numéro d’identité des passagers
- Les survivants représentés par un 1 et ceux n’ayant pas survécu représentés par un 0.
- La classe d’embarquement (1,2 ou 3).
- Noms des passagers
- Le sexe (H ou F)
- L’Age des personnes présentent dans le bateau
- La situation /relation familiale des passagers (mariés / frères sœurs)
- Parch= Représente le nombre d’enfants et parents à bord du Titanic
- Le numéro des billets
- Tarif des passagers.
- Numéros de cabine des passagers
- Le port dans lequel ils ont embarqués (Cherbourg, Queenstown et Southampton) 

La ville de départ était Southampton en Angleterre et le trajet devait se poursuivre jusqu’à New York donc il y a eu une escale à Cherbourg en France puis à Queenstown en Nouvelle Zélande.
Nous remarquons que certaines données sont manquantes notamment celle concernant le numéro de cabine. 
Certaines données n’ont pas été retranscrite celle-ci sont alors interprété comme étant nul. 




OBJECTIFS DU PROJET : 

Le but est d’exploiter les connaissances que nous allons acquérir dans ce semestre en Bdd afin de manipuler une base de données, créer des tables et répondre à certaines requêtes concernant des données réels.
Parallèlement nous allons également apprendre à faire des requêtes en langage SQL. Cela nous permet également d'avancer en fonction des cours que nous recevons, cette sae nous permet donc de passer de la théorie à la pratique. 

L’objectif secondaire est de déterminer les caractéristiques des personnes qui ont survécu et celle qui n’ont pas survécu. Ses analyses vont donc nous permettre de répondre à des questions beaucoup plus précises afin de
comprendre si certains facteurs sont liés à cette tragédie, au fait que d’autres ont survécu ou
non. Comme par exemple , savoir combien de personnes ont survécu, quelles étaient leurs situations au moment des
faits…



MODELE DE DONNEES TITANIC TRAIN :


titanic_train_csv(passagerId, survived, Pclass, Name, Sex, Age, Sibsp, Parch, Ticket, Fare, Cabin, Embarked) ;

Dom(passagerId) = valeurs numériques
Dom(survived) =valeurs numériques
Dom(Pclass) =valeurs numériques
Dom(Name) = chaine de caractère 
Dom(Sex) =chaine de caractère 
Dom(Age) =float
Dom(Sibsp) =valeur numérique 
Dom(Parch) =valeur numérique 
Dom(Ticket) =valeur numérique 
Dom(Fare) =float
Dom(Cabin)=ensemble des valeurs autorisés
Dom(Embarked) =chaine de caractère

Cardinalité = 891 Degré = 12

## PHASE 2 ##

Objectifs : 

-Creation de tables nécessaire suite à l'analyse faite des données de la base Titanic_Train_csv 
-Description des tables 
-Alimention des tables à partir du fichier


Description des tables:

table Passagers(PassagerId,survived,pclass ,name,age,sex,sibps,parch); 
table Embarquement(Ticket,Fare, Cabin,Embarked,Survived,Name,SibSp,Pclass,PassagerId);
table Titanic(PassagerId,Survived,Pclass ,Name,Age,Sex,Sibps,Parch,Fare,Cabin,Embarked);

Dans un premier temps, pour faire nos tables plusieurs paramètres étaient à prendre en compte tels que les clés primaire,les clés étrangère au sein de notre base de données.
Les differentes relations concernant nos tables étaient également à prendre en compte notamment en ce qui concerne les requetes. 
Dans ce sens, nous avons trouvé qu'il était préférable de créer trois tables différentes dont l'une est la copie conforme du fichier csv. 
Notre base de donnés est alors composé d'une table ayant des caractéristiques sur les passagers. 
Une autre dans laquelle il y a des informations concernant les embarquements 
Nous avons décidez ma camarade et moi de créer ces deux tables pour mettre en avant d'eventuelle relations entre les personnes ayant survecu et leur "situation au sein du bateau" ce qui nous permettrait de relier la table passagers et embarquement afin d'analyser une possible corrélation.

Table Passagers :

La table Passagers est une table qui continent toutes les informations nécessaires concernant les passagers à bord du Titanic. La clé primaire de la table passager est PassagerId car elle permet d’identifier les tuples au sein de la relation. Il est nécessaire de vérifié que chaque tuples soit composé d'une valeur atomique . Elle permet de différencier les éléments de la relation. La clé étrangère de la table Passagers est PassagerId faisant référence à la table Titanic.
La table passagers est donc constitué de 8 attributs et celle ci est composé de 891 lignes(autrement des tuples). 
Le degré de la table est donc de 8 et la cardinalité est de 891. 


Model de donné de la table Passager/Domaine des attributs:

PASSAGER(PassagerId,name,age,sex,sibps,parch,survived) 
dom(PassagerId)=valeurs numériques 
dom(Name)=chaine de caractère 
dom(Age)=float
dom(Sex)=chaine de caractère 
dom(Sibps)=valeur numérique
dom(Parch)=valeur numérique 
dom(Survived)=valeur numérique
dom(Sex)=chaine de caractère

Table Embarquement : 

La table embarquement suit la même logique que la table Passagers dans le sens où celle-ci contient les informations qui concernant indirectement les passagers comme par exemple, la ville dans laquelle ils ont embarqué, le numéro de leurs tickets… 
La clé primaire de cette table est donc l’attribut Name. Name fait office de clé primaire car il différencie à son tour les éléments de la relation. La clé étrangère de la table embarquement est PassagerId faisant référence à la table Titanic.
Chaque numéro de ticket est unique, il permet donc d’identifier les individus.
La table embarquement est donc constitué de 8 attributs et la cardinalité est de 891. 

Model de donné de la table Embarquement/Domaine des attributs: 

Embarquement(Ticket,embarked,cabin,fare,sibps,pclasse,PassagerId)
dom(Ticket)=valeurs numériques 
dom(Embarked)=chaine de caractère
dom(Cabin)=valeurs numériques 
dom(Fare)=float 
dom(Sibps)= valeurs numeriques
dom(Pclasse)=valeurs numériques 
dom(PassagerId)=valeurs numériques


Pour finir , nous avons créer la table TITANIC dans le bus de pourvoir reliée la table passagers et embarquement. Cela nous a aider à créer les clés étrangère.

In [203]:
%%sql

CREATE TABLE TITANIC (PassagerID int PRIMARY KEY,
                      Survived int ,
                      Pclass int , 
                      Name varchar(150),
                      Sex varchar(50),
                      Age float ,SibSp int, 
                      Parch int , 
                      Ticket varchar (150), 
                      Fare float, 
                      Cabin varchar(150), 
                      Embarked varchar (150));

 * postgresql://oceane:***@localhost/postgres
(psycopg2.errors.DuplicateTable) relation "titanic" already exists

[SQL: CREATE TABLE TITANIC (PassagerID int PRIMARY KEY,
                      Survived int ,
                      Pclass int ,
                      Name varchar(150),
                      Sex varchar(50),
                      Age float ,SibSp int,
                      Parch int ,
                      Ticket varchar (150),
                      Fare float,
                      Cabin varchar(150),
                      Embarked varchar (150));]
(Background on this error at: http://sqlalche.me/e/14/f405)

In [204]:
%%sql 
COPY TITANIC FROM '/Users/oceane/Downloads/titanic_train.csv' DELIMITER','CSV HEADER;

 * postgresql://oceane:***@localhost/postgres

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "titanic_pkey"
DETAIL:  Key (passagerid)=(1) already exists.
CONTEXT:  COPY titanic, line 2

[SQL: COPY TITANIC FROM '/Users/oceane/Downloads/titanic_train.csv' DELIMITER','CSV HEADER;]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

In [214]:
%%sql

CREATE TABLE passagers (PassagerID integer PRIMARY KEY,
                       Survived integer,
                       Pclass integer,
                       Name varchar(150),
                       Sex varchar(50),
                       Age float,
                       SibSp integer,
                       Parch integer, 
                       foreign key (PassagerID) references TITANIC (PassagerID));

 * postgresql://oceane:***@localhost/postgres
(psycopg2.errors.DuplicateTable) relation "passagers" already exists

[SQL: CREATE TABLE passagers (PassagerID integer PRIMARY KEY,
                       Survived integer,
                       Pclass integer,
                       Name varchar(150),
                       Sex varchar(50),
                       Age float,
                       SibSp integer,
                       Parch integer,
                       foreign key (PassagerID) references TITANIC (PassagerID));]
(Background on this error at: http://sqlalche.me/e/14/f405)

In [ ]:
# Un message d'erreur apparait (unique violation) 
#car nous ne pouvont pas réacffecter les valeurs alors qu'elles y sont déja.

In [215]:
%%sql 
COPY passagers FROM '/Users/oceane/Downloads/tab_passagers.csv' DELIMITER';'CSV HEADER;

 * postgresql://oceane:***@localhost/postgres

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "passagers_pkey"
DETAIL:  Key (passagerid)=(1) already exists.
CONTEXT:  COPY passagers, line 2

[SQL: COPY passagers FROM '/Users/oceane/Downloads/tab_passagers.csv' DELIMITER';'CSV HEADER;]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

In [207]:
%%sql
SELECT*FROM passagers;

 * postgresql://oceane:***@localhost/postgres
891 rows affected.

[(1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0),
 (2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', 38.0, 1, 0),
 (3, 1, 3, 'Heikkinen, Miss. Laina', 'female', 26.0, 0, 0),
 (4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', 35.0, 1, 0),
 (5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0),
 (6, 0, 3, 'Moran, Mr. James', 'male', None, 0, 0),
 (7, 0, 1, 'McCarthy, Mr. Timothy J', 'male', 54.0, 0, 0),
 (8, 0, 3, 'Palsson, Master. Gosta Leonard', 'male', 2.0, 3, 1),
 (9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'female', 27.0, 0, 2),
 (10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', 14.0, 1, 0),
 (11, 1, 3, 'Sandstrom, Miss. Marguerite Rut', 'female', 4.0, 1, 1),
 (12, 1, 1, 'Bonnell, Miss. Elizabeth', 'female', 58.0, 0, 0),
 (13, 0, 3, 'Saundercock, Mr. William Henry', 'male', 20.0, 0, 0),
 (14, 0, 3, 'Andersson, Mr. Anders Johan', 'male', 39.0, 1, 5),
 (15, 0, 3, 'Vestrom, Miss. Hulda Amanda Adolfina', 'female', 14.0, 0, 0),
 (16, 1, 2, 'Hewlett, Mrs. (Mary D Kingcome) ', 'female', 55.0, 0, 0),
 (17, 0, 3, 'Rice, Master. Eugene', 'male', 2.0, 4, 1),
 (18, 1, 2, 'Williams, Mr. Charles Eugene', 'male', None, 0, 0),
 (19, 0, 3, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'female', 31.0, 1, 0),
 (20, 1, 3, 'Masselmani, Mrs. Fatima', 'female', None, 0, 0),
 (21, 0, 2, 'Fynney, Mr. Joseph J', 'male', 35.0, 0, 0),
 (22, 1, 2, 'Beesley, Mr. Lawrence', 'male', 34.0, 0, 0),
 (23, 1, 3, 'McGowan, Miss. Anna "Annie"', 'female', 15.0, 0, 0),
 (24, 1, 1, 'Sloper, Mr. William Thompson', 'male', 28.0, 0, 0),
 (25, 0, 3, 'Palsson, Miss. Torborg Danira', 'female', 8.0, 3, 1),
 (26, 1, 3, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'female', 38.0, 1, 5),
 (27, 0, 3, 'Emir, Mr. Farred Chehab', 'male', None, 0, 0),
 (28, 0, 1, 'Fortune, Mr. Charles Alexander', 'male', 19.0, 3, 2),
 (29, 1, 3, 'O\'Dwyer, Miss. Ellen "Nellie"', 'female', None, 0, 0),
 (30, 0, 3, 'Todoroff, Mr. Lalio', 'male', None, 0, 0),
 (31, 0, 1, 'Uruchurtu, Don. Manuel E', 'male', 40.0, 0, 0),
 (32, 1, 1, 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'female', None, 1, 0),
 (33, 1, 3, 'Glynn, Miss. Mary Agatha', 'female', None, 0, 0),
 (34, 0, 2, 'Wheadon, Mr. Edward H', 'male', 66.0, 0, 0),
 (35, 0, 1, 'Meyer, Mr. Edgar Joseph', 'male', 28.0, 1, 0),
 (36, 0, 1, 'Holverson, Mr. Alexander Oskar', 'male', 42.0, 1, 0),
 (37, 1, 3, 'Mamee, Mr. Hanna', 'male', None, 0, 0),
 (38, 0, 3, 'Cann, Mr. Ernest Charles', 'male', 21.0, 0, 0),
 (39, 0, 3, 'Vander Planke, Miss. Augusta Maria', 'female', 18.0, 2, 0),
 (40, 1, 3, 'Nicola-Yarred, Miss. Jamila', 'female', 14.0, 1, 0),
 (41, 0, 3, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'female', 40.0, 1, 0),
 (42, 0, 2, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'female', 27.0, 1, 0),
 (43, 0, 3, 'Kraeff, Mr. Theodor', 'male', None, 0, 0),
 (44, 1, 2, 'Laroche, Miss. Simonne Marie Anne Andree', 'female', 3.0, 1, 2),
 (45, 1, 3, 'Devaney, Miss. Margaret Delia', 'female', 19.0, 0, 0),
 (46, 0, 3, 'Rogers, Mr. William John', 'male', None, 0, 0),
 (47, 0, 3, 'Lennon, Mr. Denis', 'male', None, 1, 0),
 (48, 1, 3, "O'Driscoll, Miss. Bridget", 'female', None, 0, 0),
 (49, 0, 3, 'Samaan, Mr. Youssef', 'male', None, 2, 0),
 (50, 0, 3, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'female', 18.0, 1, 0),
 (51, 0, 3, 'Panula, Master. Juha Niilo', 'male', 7.0, 4, 1),
 (52, 0, 3, 'Nosworthy, Mr. Richard Cater', 'male', 21.0, 0, 0),
 (53, 1, 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'female', 49.0, 1, 0),
 (54, 1, 2, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'female', 29.0, 1, 0),
 (55, 0, 1, 'Ostby, Mr. Engelhart Cornelius', 'male', 65.0, 0, 1),
 (56, 1, 1, 'Woolner, Mr. Hugh', 'male', None, 0, 0),
 (57, 1, 2, 'Rugg, Miss. Emily', 'female', 21.0, 0, 0),
 (58, 0, 3, 'Novel, Mr. Mansouer', 'male', 28.5, 0, 0),
 (59, 1, 2, 'West, Miss. Constance Mirium', 'female', 5.0, 1, 2),
 (60, 0, 3, 'Goodwin, Master. William Frederick', 'male', 11.0, 5, 2),
 (61, 0, 3, 'Sirayanian, Mr. Orsen', 'male', 22.0, 0, 0),
 (62, 1, 1, 'Icard, Miss. Amelie', 'female', 38.0, 0, 0),
 (63, 0, 1, 'Harris, Mr. Henry Birkhardt', 'male', 45.0, 1, 0),
 (64, 0, 3, 'Skoog, Master. Harald', 'male', 4.0, 3, 2),
 (65, 0, 1, 'Stewart, Mr. Albert A', 'male', None, 0, 0),
 (66, 1, 3, 'Moubarek, Master. Gerios', 'male', None, 1, 1),
 (67, 1, 2, 'Nye, Mrs. (Elizabeth Ramell)', 'female', 29.0, 0, 0),
 (68, 0, 3, 'Crease, Mr. Ernest James', 'male', 19.0, 0, 0),
 (69, 1, 3, 'Andersson, Miss. Erna Alexandra', 'female', 17.0, 4, 2),
 (70, 0, 3, 'Kink, Mr. Vincenz', 'male', 26.0, 2, 0),
 (71, 0, 2, 'Jenkin, Mr. Stephen Curnow', 'male', 32.0, 0, 0),
 (72, 0, 3, 'Goodwin, Miss. Lillian Amy', 'female', 16.0, 5, 2),
 (73, 0, 2, 'Hood, Mr. Ambrose Jr', 'male', 21.0, 0, 0),
 (74, 0, 3, 'Chronopoulos, Mr. Apostolos', 'male', 26.0, 1, 0),
 (75, 1, 3, 'Bing, Mr. Lee', 'male', 32.0, 0, 0),
 (76, 0, 3, 'Moen, Mr. Sigurd Hansen', 'male', 25.0, 0, 0),
 (77, 0, 3, 'Staneff, Mr. Ivan', 'male', None, 0, 0),
 (78, 0, 3, 'Moutal, Mr. Rahamin Haim', 'male', None, 0, 0),
 (79, 1, 2, 'Caldwell, Master. Alden Gates', 'male', 0.83, 0, 2),
 (80, 1, 3, 'Dowdell, Miss. Elizabeth', 'female', 30.0, 0, 0),
 (81, 0, 3, 'Waelens, Mr. Achille', 'male', 22.0, 0, 0),
 (82, 1, 3, 'Sheerlinck, Mr. Jan Baptist', 'male', 29.0, 0, 0),
 (83, 1, 3, 'McDermott, Miss. Brigdet Delia', 'female', None, 0, 0),
 (84, 0, 1, 'Carrau, Mr. Francisco M', 'male', 28.0, 0, 0),
 (85, 1, 2, 'Ilett, Miss. Bertha', 'female', 17.0, 0, 0),
 (86, 1, 3, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'female', 33.0, 3, 0),
 (87, 0, 3, 'Ford, Mr. William Neal', 'male', 16.0, 1, 3),
 (88, 0, 3, 'Slocovski, Mr. Selman Francis', 'male', None, 0, 0),
 (89, 1, 1, 'Fortune, Miss. Mabel Helen', 'female', 23.0, 3, 2),
 (90, 0, 3, 'Celotti, Mr. Francesco', 'male', 24.0, 0, 0),
 (91, 0, 3, 'Christmann, Mr. Emil', 'male', 29.0, 0, 0),
 (92, 0, 3, 'Andreasson, Mr. Paul Edvin', 'male', 20.0, 0, 0),
 (93, 0, 1, 'Chaffee, Mr. Herbert Fuller', 'male', 46.0, 1, 0),
 (94, 0, 3, 'Dean, Mr. Bertram Frank', 'male', 26.0, 1, 2),
 (95, 0, 3, 'Coxon, Mr. Daniel', 'male', 59.0, 0, 0),
 (96, 0, 3, 'Shorney, Mr. Charles Joseph', 'male', None, 0, 0),
 (97, 0, 1, 'Goldschmidt, Mr. George B', 'male', 71.0, 0, 0),
 (98, 1, 1, 'Greenfield, Mr. William Bertram', 'male', 23.0, 0, 1),
 (99, 1, 2, 'Doling, Mrs. John T (Ada Julia Bone)', 'female', 34.0, 0, 1),
 (100, 0, 2, 'Kantor, Mr. Sinai', 'male', 34.0, 1, 0),
 (101, 0, 3, 'Petranec, Miss. Matilda', 'female', 28.0, 0, 0),
 (102, 0, 3, 'Petroff, Mr. Pastcho ("Pentcho")', 'male', None, 0, 0),
 (103, 0, 1, 'White, Mr. Richard Frasar', 'male', 21.0, 0, 1),
 (104, 0, 3, 'Johansson, Mr. Gustaf Joel', 'male', 33.0, 0, 0),
 (105, 0, 3, 'Gustafsson, Mr. Anders Vilhelm', 'male', 37.0, 2, 0),
 (106, 0, 3, 'Mionoff, Mr. Stoytcho', 'male', 28.0, 0, 0),
 (107, 1, 3, 'Salkjelsvik, Miss. Anna Kristine', 'female', 21.0, 0, 0),
 (108, 1, 3, 'Moss, Mr. Albert Johan', 'male', None, 0, 0),
 (109, 0, 3, 'Rekic, Mr. Tido', 'male', 38.0, 0, 0),
 (110, 1, 3, 'Moran, Miss. Bertha', 'female', None, 1, 0),
 (111, 0, 1, 'Porter, Mr. Walter Chamberlain', 'male', 47.0, 0, 0),
 (112, 0, 3, 'Zabour, Miss. Hileni', 'female', 14.5, 1, 0),
 (113, 0, 3, 'Barton, Mr. David John', 'male', 22.0, 0, 0),
 (114, 0, 3, 'Jussila, Miss. Katriina', 'female', 20.0, 1, 0),
 (115, 0, 3, 'Attalah, Miss. Malake', 'female', 17.0, 0, 0),
 (116, 0, 3, 'Pekoniemi, Mr. Edvard', 'male', 21.0, 0, 0),
 (117, 0, 3, 'Connors, Mr. Patrick', 'male', 70.5, 0, 0),
 (118, 0, 2, 'Turpin, Mr. William John Robert', 'male', 29.0, 1, 0),
 (119, 0, 1, 'Baxter, Mr. Quigg Edmond', 'male', 24.0, 0, 1),
 (120, 0, 3, 'Andersson, Miss. Ellis Anna Maria', 'female', 2.0, 4, 2),
 (121, 0, 2, 'Hickman, Mr. Stanley George', 'male', 21.0, 2, 0),
 (122, 0, 3, 'Moore, Mr. Leonard Charles', 'male', None, 0, 0),
 (123, 0, 2, 'Nasser, Mr. Nicholas', 'male', 32.5, 1, 0),
 (124, 1, 2, 'Webber, Miss. Susan', 'female', 32.5, 0, 0),
 (125, 0, 1, 'White, Mr. Percival Wayland', 'male', 54.0, 0, 1),
 (126, 1, 3, 'Nicola-Yarred, Master. Elias', 'male', 12.0, 1, 0),
 (127, 0, 3, 'McMahon, Mr. Martin', 'male', None, 0, 0),
 (128, 1, 3, 'Madsen, Mr. Fridtjof Arne', 'male', 24.0, 0, 0),
 (129, 1, 3, 'Peter, Miss. Anna', 'female', None, 1, 1),
 (130, 0, 3, 'Ekstrom, Mr. Johan', 'male', 45.0, 0, 0),
 (131, 0, 3, 'Drazenoic, Mr. Jozef', 'male', 33.0, 0, 0),
 (132, 0, 3, 'Coelho, Mr. Domingos Fernandeo', 'male', 20.0, 0, 0),
 (133, 0, 3, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 'female', 47.0, 1, 0),
 (134, 1, 2, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 'female', 29.0, 1, 0),
 (135, 0, 2, 'Sobey, Mr. Samuel James Hayden', 'male', 25.0, 0, 0),
 (136, 0, 2, 'Richard, Mr. Emile', 'male', 23.0, 0, 0),
 (137, 1, 1, 'Newsom, Miss. Helen Monypeny', 'female', 19.0, 0, 2),
 (138, 0, 1, 'Futrelle, Mr. Jacques Heath', 'male', 37.0, 1, 0),
 (139, 0, 3, 'Osen, Mr. Olaf Elon', 'male', 16.0, 0, 0),
 (140, 0, 1, 'Giglio, Mr. Victor', 'male', 24.0, 0, 0),
 (141, 0, 3, 'Boulos, Mrs. Joseph (Sultana)', 'female', None, 0, 2),
 (142, 1, 3, 'Nysten, Miss. Anna Sofia', 'female', 22.0, 0, 0),
 (143, 1, 3, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 'female', 24.0, 1, 0),
 (144, 0, 3, 'Burke, Mr. Jeremiah', 'male', 19.0, 0, 0),
 (145, 0, 2, 'Andrew, Mr. Edgardo Samuel', 'male', 18.0, 0, 0),
 (146, 0, 2, 'Nicholls, Mr. Joseph Charles', 'male', 19.0, 1, 1),
 (147, 1, 3, 'Andersson, Mr. August Edvard ("Wennerstrom")', 'male', 27.0, 0, 0),
 (148, 0, 3, 'Ford, Miss. Robina Maggie "Ruby"', 'female', 9.0, 2, 2),
 (149, 0, 2, 'Navratil, Mr. Michel ("Louis M Hoffman")', 'male', 36.5, 0, 2),
 (150, 0, 2, 'Byles, Rev. Thomas Roussel Davids', 'male', 42.0, 0, 0),
 (151, 0, 2, 'Bateman, Rev. Robert James', 'male', 51.0, 0, 0),
 (152, 1, 1, 'Pears, Mrs. Thomas (Edith Wearne)', 'female', 22.0, 1, 0),
 (153, 0, 3, 'Meo, Mr. Alfonzo', 'male', 55.5, 0, 0),
 (154, 0, 3, 'van Billiard, Mr. Austin Blyler', 'male', 40.5, 0, 2),
 (155, 0, 3, 'Olsen, Mr. Ole Martin', 'male', None, 0, 0),
 (156, 0, 1, 'Williams, Mr. Charles Duane', 'male', 51.0, 0, 1),
 (157, 1, 3, 'Gilnagh, Miss. Katherine "Katie"', 'female', 16.0, 0, 0),
 (158, 0, 3, 'Corn, Mr. Harry', 'male', 30.0, 0, 0),
 (159, 0, 3, 'Smiljanic, Mr. Mile', 'male', None, 0, 0),
 (160, 0, 3, 'Sage, Master. Thomas Henry', 'male', None, 8, 2),
 (161, 0, 3, 'Cribb, Mr. John Hatfield', 'male', 44.0, 0, 1),
 (162, 1, 2, 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 'female', 40.0, 0, 0),
 (163, 0, 3, 'Bengtsson, Mr. John Viktor', 'male', 26.0, 0, 0),
 (164, 0, 3, 'Calic, Mr. Jovo', 'male', 17.0, 0, 0),
 (165, 0, 3, 'Panula, Master. Eino Viljami', 'male', 1.0, 4, 1),
 (166, 1, 3, 'Goldsmith, Master. Frank John William "Frankie"', 'male', 9.0, 0, 2),
 (167, 1, 1, 'Chibnall, Mrs. (Edith Martha Bowerman)', 'female', None, 0, 1),
 (168, 0, 3, 'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 'female', 45.0, 1, 4),
 (169, 0, 1, 'Baumann, Mr. John D', 'male', None, 0, 0),
 (170, 0, 3, 'Ling, Mr. Lee', 'male', 28.0, 0, 0),
 (171, 0, 1, 'Van der hoef, Mr. Wyckoff', 'male', 61.0, 0, 0),
 (172, 0, 3, 'Rice, Master. Arthur', 'male', 4.0, 4, 1),
 (173, 1, 3, 'Johnson, Miss. Eleanor Ileen', 'female', 1.0, 1, 1),
 (174, 0, 3, 'Sivola, Mr. Antti Wilhelm', 'male', 21.0, 0, 0),
 (175, 0, 1, 'Smith, Mr. James Clinch', 'male', 56.0, 0, 0),
 (176, 0, 3, 'Klasen, Mr. Klas Albin', 'male', 18.0, 1, 1),
 (177, 0, 3, 'Lefebre, Master. Henry Forbes', 'male', None, 3, 1),
 (178, 0, 1, 'Isham, Miss. Ann Elizabeth', 'female', 50.0, 0, 0),
 (179, 0, 2, 'Hale, Mr. Reginald', 'male', 30.0, 0, 0),
 (180, 0, 3, 'Leonard, Mr. Lionel', 'male', 36.0, 0, 0),
 (181, 0, 3, 'Sage, Miss. Constance Gladys', 'female', None, 8, 2),
 (182, 0, 2, 'Pernot, Mr. Rene', 'male', None, 0, 0),
 (183, 0, 3, 'Asplund, Master. Clarence Gustaf Hugo', 'male', 9.0, 4, 2),
 (184, 1, 2, 'Becker, Master. Richard F', 'male', 1.0, 2, 1),
 (185, 1, 3, 'Kink-Heilmann, Miss. Luise Gretchen', 'female', 4.0, 0, 2),
 (186, 0, 1, 'Rood, Mr. Hugh Roscoe', 'male', None, 0, 0),
 (187, 1, 3, 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 'female', None, 1, 0),
 (188, 1, 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'male', 45.0, 0, 0),
 (189, 0, 3, 'Bourke, Mr. John', 'male', 40.0, 1, 1),
 (190, 0, 3, 'Turcin, Mr. Stjepan', 'male', 36.0, 0, 0),
 (191, 1, 2, 'Pinsky, Mrs. (Rosa)', 'female', 32.0, 0, 0),
 (192, 0, 2, 'Carbines, Mr. William', 'male', 19.0, 0, 0),
 (193, 1, 3, 'Andersen-Jensen, Miss. Carla Christine Nielsine', 'female', 19.0, 1, 0),
 (194, 1, 2, 'Navratil, Master. Michel M', 'male', 3.0, 1, 1),
 (195, 1, 1, 'Brown, Mrs. James Joseph (Margaret Tobin)', 'female', 44.0, 0, 0),
 (196, 1, 1, 'Lurette, Miss. Elise', 'female', 58.0, 0, 0),
 (197, 0, 3, 'Mernagh, Mr. Robert', 'male', None, 0, 0),
 (198, 0, 3, 'Olsen, Mr. Karl Siegwart Andreas', 'male', 42.0, 0, 1),
 (199, 1, 3, 'Madigan, Miss. Margaret "Maggie"', 'female', None, 0, 0),
 (200, 0, 2, 'Yrois, Miss. Henriette ("Mrs Harbeck")', 'female', 24.0, 0, 0),
 (201, 0, 3, 'Vande Walle, Mr. Nestor Cyriel', 'male', 28.0, 0, 0),
 (202, 0, 3, 'Sage, Mr. Frederick', 'male', None, 8, 2),
 (203, 0, 3, 'Johanson, Mr. Jakob Alfred', 'male', 34.0, 0, 0),
 (204, 0, 3, 'Youseff, Mr. Gerious', 'male', 45.5, 0, 0),
 (205, 1, 3, 'Cohen, Mr. Gurshon "Gus"', 'male', 18.0, 0, 0),
 (206, 0, 3, 'Strom, Miss. Telma Matilda', 'female', 2.0, 0, 1),
 (207, 0, 3, 'Backstrom, Mr. Karl Alfred', 'male', 32.0, 1, 0),
 (208, 1, 3, 'Albimona, Mr. Nassef Cassem', 'male', 26.0, 0, 0),
 (209, 1, 3, 'Carr, Miss. Helen "Ellen"', 'female', 16.0, 0, 0),
 (210, 1, 1, 'Blank, Mr. Henry', 'male', 40.0, 0, 0),
 (211, 0, 3, 'Ali, Mr. Ahmed', 'male', 24.0, 0, 0),
 (212, 1, 2, 'Cameron, Miss. Clear Annie', 'female', 35.0, 0, 0),
 (213, 0, 3, 'Perkin, Mr. John Henry', 'male', 22.0, 0, 0),
 (214, 0, 2, 'Givard, Mr. Hans Kristensen', 'male', 30.0, 0, 0),
 (215, 0, 3, 'Kiernan, Mr. Philip', 'male', None, 1, 0),
 (216, 1, 1, 'Newell, Miss. Madeleine', 'female', 31.0, 1, 0),
 (217, 1, 3, 'Honkanen, Miss. Eliina', 'female', 27.0, 0, 0),
 (218, 0, 2, 'Jacobsohn, Mr. Sidney Samuel', 'male', 42.0, 1, 0),
 (219, 1, 1, 'Bazzani, Miss. Albina', 'female', 32.0, 0, 0),
 (220, 0, 2, 'Harris, Mr. Walter', 'male', 30.0, 0, 0),
 (221, 1, 3, 'Sunderland, Mr. Victor Francis', 'male', 16.0, 0, 0),
 (222, 0, 2, 'Bracken, Mr. James H', 'male', 27.0, 0, 0),
 (223, 0, 3, 'Green, Mr. George Henry', 'male', 51.0, 0, 0),
 (224, 0, 3, 'Nenkoff, Mr. Christo', 'male', None, 0, 0),
 (225, 1, 1, 'Hoyt, Mr. Frederick Maxfield', 'male', 38.0, 1, 0),
 (226, 0, 3, 'Berglund, Mr. Karl Ivar Sven', 'male', 22.0, 0, 0),
 (227, 1, 2, 'Mellors, Mr. William John', 'male', 19.0, 0, 0),
 (228, 0, 3, 'Lovell, Mr. John Hall ("Henry")', 'male', 20.5, 0, 0),
 (229, 0, 2, 'Fahlstrom, Mr. Arne Jonas', 'male', 18.0, 0, 0),
 (230, 0, 3, 'Lefebre, Miss. Mathilde', 'female', None, 3, 1),
 (231, 1, 1, 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 'female', 35.0, 1, 0),
 (232, 0, 3, 'Larsson, Mr. Bengt Edvin', 'male', 29.0, 0, 0),
 (233, 0, 2, 'Sjostedt, Mr. Ernst Adolf', 'male', 59.0, 0, 0),
 (234, 1, 3, 'Asplund, Miss. Lillian Gertrud', 'female', 5.0, 4, 2),
 (235, 0, 2, 'Leyson, Mr. Robert William Norman', 'male', 24.0, 0, 0),
 (236, 0, 3, 'Harknett, Miss. Alice Phoebe', 'female', None, 0, 0),
 (237, 0, 2, 'Hold, Mr. Stephen', 'male', 44.0, 1, 0),
 (238, 1, 2, 'Collyer, Miss. Marjorie "Lottie"', 'female', 8.0, 0, 2),
 (239, 0, 2, 'Pengelly, Mr. Frederick William', 'male', 19.0, 0, 0),
 (240, 0, 2, 'Hunt, Mr. George Henry', 'male', 33.0, 0, 0),
 (241, 0, 3, 'Zabour, Miss. Thamine', 'female', None, 1, 0),
 (242, 1, 3, 'Murphy, Miss. Katherine "Kate"', 'female', None, 1, 0),
 (243, 0, 2, 'Coleridge, Mr. Reginald Charles', 'male', 29.0, 0, 0),
 (244, 0, 3, 'Maenpaa, Mr. Matti Alexanteri', 'male', 22.0, 0, 0),
 (245, 0, 3, 'Attalah, Mr. Sleiman', 'male', 30.0, 0, 0),
 (246, 0, 1, 'Minahan, Dr. William Edward', 'male', 44.0, 2, 0),
 (247, 0, 3, 'Lindahl, Miss. Agda Thorilda Viktoria', 'female', 25.0, 0, 0),
 (248, 1, 2, 'Hamalainen, Mrs. William (Anna)', 'female', 24.0, 0, 2),
 (249, 1, 1, 'Beckwith, Mr. Richard Leonard', 'male', 37.0, 1, 1),
 (250, 0, 2, 'Carter, Rev. Ernest Courtenay', 'male', 54.0, 1, 0),
 (251, 0, 3, 'Reed, Mr. James George', 'male', None, 0, 0),
 (252, 0, 3, 'Strom, Mrs. Wilhelm (Elna Matilda Persson)', 'female', 29.0, 1, 1),
 (253, 0, 1, 'Stead, Mr. William Thomas', 'male', 62.0, 0, 0),
 (254, 0, 3, 'Lobb, Mr. William Arthur', 'male', 30.0, 1, 0),
 (255, 0, 3, 'Rosblom, Mrs. Viktor (Helena Wilhelmina)', 'female', 41.0, 0, 2),
 (256, 1, 3, 'Touma, Mrs. Darwis (Hanne Youssef Razi)', 'female', 29.0, 0, 2),
 (257, 1, 1, 'Thorne, Mrs. Gertrude Maybelle', 'female', None, 0, 0),
 (258, 1, 1, 'Cherry, Miss. Gladys', 'female', 30.0, 0, 0),
 (259, 1, 1, 'Ward, Miss. Anna', 'female', 35.0, 0, 0),
 (260, 1, 2, 'Parrish, Mrs. (Lutie Davis)', 'female', 50.0, 0, 1),
 (261, 0, 3, 'Smith, Mr. Thomas', 'male', None, 0, 0),
 (262, 1, 3, 'Asplund, Master. Edvin Rojj Felix', 'male', 3.0, 4, 2),
 (263, 0, 1, 'Taussig, Mr. Emil', 'male', 52.0, 1, 1),
 (264, 0, 1, 'Harrison, Mr. William', 'male', 40.0, 0, 0),
 (265, 0, 3, 'Henry, Miss. Delia', 'female', None, 0, 0),
 (266, 0, 2, 'Reeves, Mr. David', 'male', 36.0, 0, 0),
 (267, 0, 3, 'Panula, Mr. Ernesti Arvid', 'male', 16.0, 4, 1),
 (268, 1, 3, 'Persson, Mr. Ernst Ulrik', 'male', 25.0, 1, 0),
 (269, 1, 1, 'Graham, Mrs. William Thompson (Edith Junkins)', 'female', 58.0, 0, 1),
 (270, 1, 1, 'Bissette, Miss. Amelia', 'female', 35.0, 0, 0),
 (271, 0, 1, 'Cairns, Mr. Alexander', 'male', None, 0, 0),
 (272, 1, 3, 'Tornquist, Mr. William Henry', 'male', 25.0, 0, 0),
 (273, 1, 2, 'Mellinger, Mrs. (Elizabeth Anne Maidment)', 'female', 41.0, 0, 1),
 (274, 0, 1, 'Natsch, Mr. Charles H', 'male', 37.0, 0, 1),
 (275, 1, 3, 'Healy, Miss. Hanora "Nora"', 'female', None, 0, 0),
 (276, 1, 1, 'Andrews, Miss. Kornelia Theodosia', 'female', 63.0, 1, 0),
 (277, 0, 3, 'Lindblom, Miss. Augusta Charlotta', 'female', 45.0, 0, 0),
 (278, 0, 2, 'Parkes, Mr. Francis "Frank"', 'male', None, 0, 0),
 (279, 0, 3, 'Rice, Master. Eric', 'male', 7.0, 4, 1),
 (280, 1, 3, 'Abbott, Mrs. Stanton (Rosa Hunt)', 'female', 35.0, 1, 1),
 (281, 0, 3, 'Duane, Mr. Frank', 'male', 65.0, 0, 0),
 (282, 0, 3, 'Olsson, Mr. Nils Johan Goransson', 'male', 28.0, 0, 0),
 (283, 0, 3, 'de Pelsmaeker, Mr. Alfons', 'male', 16.0, 0, 0),
 (284, 1, 3, 'Dorking, Mr. Edward Arthur', 'male', 19.0, 0, 0),
 (285, 0, 1, 'Smith, Mr. Richard William', 'male', None, 0, 0),
 (286, 0, 3, 'Stankovic, Mr. Ivan', 'male', 33.0, 0, 0),
 (287, 1, 3, 'de Mulder, Mr. Theodore', 'male', 30.0, 0, 0),
 (288, 0, 3, 'Naidenoff, Mr. Penko', 'male', 22.0, 0, 0),
 (289, 1, 2, 'Hosono, Mr. Masabumi', 'male', 42.0, 0, 0),
 (290, 1, 3, 'Connolly, Miss. Kate', 'female', 22.0, 0, 0),
 (291, 1, 1, 'Barber, Miss. Ellen "Nellie"', 'female', 26.0, 0, 0),
 (292, 1, 1, 'Bishop, Mrs. Dickinson H (Helen Walton)', 'female', 19.0, 1, 0),
 (293, 0, 2, 'Levy, Mr. Rene Jacques', 'male', 36.0, 0, 0),
 (294, 0, 3, 'Haas, Miss. Aloisia', 'female', 24.0, 0, 0),
 (295, 0, 3, 'Mineff, Mr. Ivan', 'male', 24.0, 0, 0),
 (296, 0, 1, 'Lewy, Mr. Ervin G', 'male', None, 0, 0),
 (297, 0, 3, 'Hanna, Mr. Mansour', 'male', 23.5, 0, 0),
 (298, 0, 1, 'Allison, Miss. Helen Loraine', 'female', 2.0, 1, 2),
 (299, 1, 1, 'Saalfeld, Mr. Adolphe', 'male', None, 0, 0),
 (300, 1, 1, 'Baxter, Mrs. James (Helene DeLaudeniere Chaput)', 'female', 50.0, 0, 1),
 (301, 1, 3, 'Kelly, Miss. Anna Katherine "Annie Kate"', 'female', None, 0, 0),
 (302, 1, 3, 'McCoy, Mr. Bernard', 'male', None, 2, 0),
 (303, 0, 3, 'Johnson, Mr. William Cahoone Jr', 'male', 19.0, 0, 0),
 (304, 1, 2, 'Keane, Miss. Nora A', 'female', None, 0, 0),
 (305, 0, 3, 'Williams, Mr. Howard Hugh "Harry"', 'male', None, 0, 0),
 (306, 1, 1, 'Allison, Master. Hudson Trevor', 'male', 0.92, 1, 2),
 (307, 1, 1, 'Fleming, Miss. Margaret', 'female', None, 0, 0),

In [208]:
%%sql
DROP TABLE IF EXISTS embarquement;
CREATE TABLE embarquement(Ticket varchar(50)  , 
                          Fare float,
                          Cabin varchar(150),
                          Embarked varchar(50),
                          Survived integer,
                          Name varchar(150) PRIMARY KEY,
                          SibSp integer,
                          Pclass integer,PassagerID integer , 
                          foreign key (PassagerID) references TITANIC (PassagerID));

 * postgresql://oceane:***@localhost/postgres
Done.
Done.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [209]:
%%sql 
COPY embarquement FROM '/Users/oceane/Downloads/table_embarquement-2.csv' DELIMITER';'CSV HEADER;

 * postgresql://oceane:***@localhost/postgres
891 rows affected.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [210]:
%%sql
SELECT*FROM embarquement

 * postgresql://oceane:***@localhost/postgres
891 rows affected.

[('A/5 21171', 7.25, None, 'S', 0, 'Braund, Mr. Owen Harris', 1, 3, 1),
 ('PC 17599', 71.2833, 'C85', 'C', 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 1, 1, 2),
 ('STON/O2. 3101282', 7.925, None, 'S', 1, 'Heikkinen, Miss. Laina', 0, 3, 3),
 ('113803', 53.1, 'C123', 'S', 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 1, 1, 4),
 ('373450', 8.05, None, 'S', 0, 'Allen, Mr. William Henry', 0, 3, 5),
 ('330877', 8.4583, None, 'Q', 0, 'Moran, Mr. James', 0, 3, 6),
 ('17463', 51.8625, 'E46', 'S', 0, 'McCarthy, Mr. Timothy J', 0, 1, 7),
 ('349909', 21.075, None, 'S', 0, 'Palsson, Master. Gosta Leonard', 3, 3, 8),
 ('347742', 11.1333, None, 'S', 1, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 0, 3, 9),
 ('237736', 30.0708, None, 'C', 1, 'Nasser, Mrs. Nicholas (Adele Achem)', 1, 2, 10),
 ('PP 9549', 16.7, 'G6', 'S', 1, 'Sandstrom, Miss. Marguerite Rut', 1, 3, 11),
 ('113783', 26.55, 'C103', 'S', 1, 'Bonnell, Miss. Elizabeth', 0, 1, 12),
 ('A/5. 2151', 8.05, None, 'S', 0, 'Saundercock, Mr. William Henry', 0, 3, 13),
 ('347082', 31.275, None, 'S', 0, 'Andersson, Mr. Anders Johan', 1, 3, 14),
 ('350406', 7.8542, None, 'S', 0, 'Vestrom, Miss. Hulda Amanda Adolfina', 0, 3, 15),
 ('248706', 16.0, None, 'S', 1, 'Hewlett, Mrs. (Mary D Kingcome) ', 0, 2, 16),
 ('382652', 29.125, None, 'Q', 0, 'Rice, Master. Eugene', 4, 3, 17),
 ('244373', 13.0, None, 'S', 1, 'Williams, Mr. Charles Eugene', 0, 2, 18),
 ('345763', 18.0, None, 'S', 0, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 1, 3, 19),
 ('2649', 7.225, None, 'C', 1, 'Masselmani, Mrs. Fatima', 0, 3, 20),
 ('239865', 26.0, None, 'S', 0, 'Fynney, Mr. Joseph J', 0, 2, 21),
 ('248698', 13.0, 'D56', 'S', 1, 'Beesley, Mr. Lawrence', 0, 2, 22),
 ('330923', 8.0292, None, 'Q', 1, 'McGowan, Miss. Anna "Annie"', 0, 3, 23),
 ('113788', 35.5, 'A6', 'S', 1, 'Sloper, Mr. William Thompson', 0, 1, 24),
 ('349909', 21.075, None, 'S', 0, 'Palsson, Miss. Torborg Danira', 3, 3, 25),
 ('347077', 31.3875, None, 'S', 1, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 1, 3, 26),
 ('2631', 7.225, None, 'C', 0, 'Emir, Mr. Farred Chehab', 0, 3, 27),
 ('19950', 263.0, 'C23 C25 C27', 'S', 0, 'Fortune, Mr. Charles Alexander', 3, 1, 28),
 ('330959', 7.8792, None, 'Q', 1, 'O\'Dwyer, Miss. Ellen "Nellie"', 0, 3, 29),
 ('349216', 7.8958, None, 'S', 0, 'Todoroff, Mr. Lalio', 0, 3, 30),
 ('PC 17601', 27.7208, None, 'C', 0, 'Uruchurtu, Don. Manuel E', 0, 1, 31),
 ('PC 17569', 146.5208, 'B78', 'C', 1, 'Spencer, Mrs. William Augustus (Marie Eugenie)', 1, 1, 32),
 ('335677', 7.75, None, 'Q', 1, 'Glynn, Miss. Mary Agatha', 0, 3, 33),
 ('C.A. 24579', 10.5, None, 'S', 0, 'Wheadon, Mr. Edward H', 0, 2, 34),
 ('PC 17604', 82.1708, None, 'C', 0, 'Meyer, Mr. Edgar Joseph', 1, 1, 35),
 ('113789', 52.0, None, 'S', 0, 'Holverson, Mr. Alexander Oskar', 1, 1, 36),
 ('2677', 7.2292, None, 'C', 1, 'Mamee, Mr. Hanna', 0, 3, 37),
 ('A./5. 2152', 8.05, None, 'S', 0, 'Cann, Mr. Ernest Charles', 0, 3, 38),
 ('345764', 18.0, None, 'S', 0, 'Vander Planke, Miss. Augusta Maria', 2, 3, 39),
 ('2651', 11.2417, None, 'C', 1, 'Nicola-Yarred, Miss. Jamila', 1, 3, 40),
 ('7546', 9.475, None, 'S', 0, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 1, 3, 41),
 ('11668', 21.0, None, 'S', 0, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 1, 2, 42),
 ('349253', 7.8958, None, 'C', 0, 'Kraeff, Mr. Theodor', 0, 3, 43),
 ('SC/Paris 2123', 41.5792, None, 'C', 1, 'Laroche, Miss. Simonne Marie Anne Andree', 1, 2, 44),
 ('330958', 7.8792, None, 'Q', 1, 'Devaney, Miss. Margaret Delia', 0, 3, 45),
 ('S.C./A.4. 23567', 8.05, None, 'S', 0, 'Rogers, Mr. William John', 0, 3, 46),
 ('370371', 15.5, None, 'Q', 0, 'Lennon, Mr. Denis', 1, 3, 47),
 ('14311', 7.75, None, 'Q', 1, "O'Driscoll, Miss. Bridget", 0, 3, 48),
 ('2662', 21.6792, None, 'C', 0, 'Samaan, Mr. Youssef', 2, 3, 49),
 ('349237', 17.8, None, 'S', 0, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 1, 3, 50),
 ('3101295', 39.6875, None, 'S', 0, 'Panula, Master. Juha Niilo', 4, 3, 51),
 ('A/4. 39886', 7.8, None, 'S', 0, 'Nosworthy, Mr. Richard Cater', 0, 3, 52),
 ('PC 17572', 76.7292, 'D33', 'C', 1, 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 1, 1, 53),
 ('2926', 26.0, None, 'S', 1, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 1, 2, 54),
 ('113509', 61.9792, 'B30', 'C', 0, 'Ostby, Mr. Engelhart Cornelius', 0, 1, 55),
 ('19947', 35.5, 'C52', 'S', 1, 'Woolner, Mr. Hugh', 0, 1, 56),
 ('C.A. 31026', 10.5, None, 'S', 1, 'Rugg, Miss. Emily', 0, 2, 57),
 ('2697', 7.2292, None, 'C', 0, 'Novel, Mr. Mansouer', 0, 3, 58),
 ('C.A. 34651', 27.75, None, 'S', 1, 'West, Miss. Constance Mirium', 1, 2, 59),
 ('CA 2144', 46.9, None, 'S', 0, 'Goodwin, Master. William Frederick', 5, 3, 60),
 ('2669', 7.2292, None, 'C', 0, 'Sirayanian, Mr. Orsen', 0, 3, 61),
 ('113572', 80.0, 'B28', None, 1, 'Icard, Miss. Amelie', 0, 1, 62),
 ('36973', 83.475, 'C83', 'S', 0, 'Harris, Mr. Henry Birkhardt', 1, 1, 63),
 ('347088', 27.9, None, 'S', 0, 'Skoog, Master. Harald', 3, 3, 64),
 ('PC 17605', 27.7208, None, 'C', 0, 'Stewart, Mr. Albert A', 0, 1, 65),
 ('2661', 15.2458, None, 'C', 1, 'Moubarek, Master. Gerios', 1, 3, 66),
 ('C.A. 29395', 10.5, 'F33', 'S', 1, 'Nye, Mrs. (Elizabeth Ramell)', 0, 2, 67),
 ('S.P. 3464', 8.1583, None, 'S', 0, 'Crease, Mr. Ernest James', 0, 3, 68),
 ('3101281', 7.925, None, 'S', 1, 'Andersson, Miss. Erna Alexandra', 4, 3, 69),
 ('315151', 8.6625, None, 'S', 0, 'Kink, Mr. Vincenz', 2, 3, 70),
 ('C.A. 33111', 10.5, None, 'S', 0, 'Jenkin, Mr. Stephen Curnow', 0, 2, 71),
 ('CA 2144', 46.9, None, 'S', 0, 'Goodwin, Miss. Lillian Amy', 5, 3, 72),
 ('S.O.C. 14879', 73.5, None, 'S', 0, 'Hood, Mr. Ambrose Jr', 0, 2, 73),
 ('2680', 14.4542, None, 'C', 0, 'Chronopoulos, Mr. Apostolos', 1, 3, 74),
 ('1601', 56.4958, None, 'S', 1, 'Bing, Mr. Lee', 0, 3, 75),
 ('348123', 7.65, 'F G73', 'S', 0, 'Moen, Mr. Sigurd Hansen', 0, 3, 76),
 ('349208', 7.8958, None, 'S', 0, 'Staneff, Mr. Ivan', 0, 3, 77),
 ('374746', 8.05, None, 'S', 0, 'Moutal, Mr. Rahamin Haim', 0, 3, 78),
 ('248738', 29.0, None, 'S', 1, 'Caldwell, Master. Alden Gates', 0, 2, 79),
 ('364516', 12.475, None, 'S', 1, 'Dowdell, Miss. Elizabeth', 0, 3, 80),
 ('345767', 9.0, None, 'S', 0, 'Waelens, Mr. Achille', 0, 3, 81),
 ('345779', 9.5, None, 'S', 1, 'Sheerlinck, Mr. Jan Baptist', 0, 3, 82),
 ('330932', 7.7875, None, 'Q', 1, 'McDermott, Miss. Brigdet Delia', 0, 3, 83),
 ('113059', 47.1, None, 'S', 0, 'Carrau, Mr. Francisco M', 0, 1, 84),
 ('SO/C 14885', 10.5, None, 'S', 1, 'Ilett, Miss. Bertha', 0, 2, 85),
 ('3101278', 15.85, None, 'S', 1, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 3, 3, 86),
 ('W./C. 6608', 34.375, None, 'S', 0, 'Ford, Mr. William Neal', 1, 3, 87),
 ('SOTON/OQ 392086', 8.05, None, 'S', 0, 'Slocovski, Mr. Selman Francis', 0, 3, 88),
 ('19950', 263.0, 'C23 C25 C27', 'S', 1, 'Fortune, Miss. Mabel Helen', 3, 1, 89),
 ('343275', 8.05, None, 'S', 0, 'Celotti, Mr. Francesco', 0, 3, 90),
 ('343276', 8.05, None, 'S', 0, 'Christmann, Mr. Emil', 0, 3, 91),
 ('347466', 7.8542, None, 'S', 0, 'Andreasson, Mr. Paul Edvin', 0, 3, 92),
 ('W.E.P. 5734', 61.175, 'E31', 'S', 0, 'Chaffee, Mr. Herbert Fuller', 1, 1, 93),
 ('C.A. 2315', 20.575, None, 'S', 0, 'Dean, Mr. Bertram Frank', 1, 3, 94),
 ('364500', 7.25, None, 'S', 0, 'Coxon, Mr. Daniel', 0, 3, 95),
 ('374910', 8.05, None, 'S', 0, 'Shorney, Mr. Charles Joseph', 0, 3, 96),
 ('PC 17754', 34.6542, 'A5', 'C', 0, 'Goldschmidt, Mr. George B', 0, 1, 97),
 ('PC 17759', 63.3583, 'D10 D12', 'C', 1, 'Greenfield, Mr. William Bertram', 0, 1, 98),
 ('231919', 23.0, None, 'S', 1, 'Doling, Mrs. John T (Ada Julia Bone)', 0, 2, 99),
 ('244367', 26.0, None, 'S', 0, 'Kantor, Mr. Sinai', 1, 2, 100),
 ('349245', 7.8958, None, 'S', 0, 'Petranec, Miss. Matilda', 0, 3, 101),
 ('349215', 7.8958, None, 'S', 0, 'Petroff, Mr. Pastcho ("Pentcho")', 0, 3, 102),
 ('35281', 77.2875, 'D26', 'S', 0, 'White, Mr. Richard Frasar', 0, 1, 103),
 ('7540', 8.6542, None, 'S', 0, 'Johansson, Mr. Gustaf Joel', 0, 3, 104),
 ('3101276', 7.925, None, 'S', 0, 'Gustafsson, Mr. Anders Vilhelm', 2, 3, 105),
 ('349207', 7.8958, None, 'S', 0, 'Mionoff, Mr. Stoytcho', 0, 3, 106),
 ('343120', 7.65, None, 'S', 1, 'Salkjelsvik, Miss. Anna Kristine', 0, 3, 107),
 ('312991', 7.775, None, 'S', 1, 'Moss, Mr. Albert Johan', 0, 3, 108),
 ('349249', 7.8958, None, 'S', 0, 'Rekic, Mr. Tido', 0, 3, 109),
 ('371110', 24.15, None, 'Q', 1, 'Moran, Miss. Bertha', 1, 3, 110),
 ('110465', 52.0, 'C110', 'S', 0, 'Porter, Mr. Walter Chamberlain', 0, 1, 111),
 ('2665', 14.4542, None, 'C', 0, 'Zabour, Miss. Hileni', 1, 3, 112),
 ('324669', 8.05, None, 'S', 0, 'Barton, Mr. David John', 0, 3, 113),
 ('4136', 9.825, None, 'S', 0, 'Jussila, Miss. Katriina', 1, 3, 114),
 ('2627', 14.4583, None, 'C', 0, 'Attalah, Miss. Malake', 0, 3, 115),
 ('STON/O 2. 3101294', 7.925, None, 'S', 0, 'Pekoniemi, Mr. Edvard', 0, 3, 116),
 ('370369', 7.75, None, 'Q', 0, 'Connors, Mr. Patrick', 0, 3, 117),
 ('11668', 21.0, None, 'S', 0, 'Turpin, Mr. William John Robert', 1, 2, 118),
 ('PC 17558', 247.5208, 'B58 B60', 'C', 0, 'Baxter, Mr. Quigg Edmond', 0, 1, 119),
 ('347082', 31.275, None, 'S', 0, 'Andersson, Miss. Ellis Anna Maria', 4, 3, 120),
 ('S.O.C. 14879', 73.5, None, 'S', 0, 'Hickman, Mr. Stanley George', 2, 2, 121),
 ('A4. 54510', 8.05, None, 'S', 0, 'Moore, Mr. Leonard Charles', 0, 3, 122),
 ('237736', 30.0708, None, 'C', 0, 'Nasser, Mr. Nicholas', 1, 2, 123),
 ('27267', 13.0, 'E101', 'S', 1, 'Webber, Miss. Susan', 0, 2, 124),
 ('35281', 77.2875, 'D26', 'S', 0, 'White, Mr. Percival Wayland', 0, 1, 125),
 ('2651', 11.2417, None, 'C', 1, 'Nicola-Yarred, Master. Elias', 1, 3, 126),
 ('370372', 7.75, None, 'Q', 0, 'McMahon, Mr. Martin', 0, 3, 127),
 ('C 17369', 7.1417, None, 'S', 1, 'Madsen, Mr. Fridtjof Arne', 0, 3, 128),
 ('2668', 22.3583, 'F E69', 'C', 1, 'Peter, Miss. Anna', 1, 3, 129),
 ('347061', 6.975, None, 'S', 0, 'Ekstrom, Mr. Johan', 0, 3, 130),
 ('349241', 7.8958, None, 'C', 0, 'Drazenoic, Mr. Jozef', 0, 3, 131),
 ('SOTON/O.Q. 3101307', 7.05, None, 'S', 0, 'Coelho, Mr. Domingos Fernandeo', 0, 3, 132),
 ('A/5. 3337', 14.5, None, 'S', 0, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 1, 3, 133),
 ('228414', 26.0, None, 'S', 1, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 1, 2, 134),
 ('C.A. 29178', 13.0, None, 'S', 0, 'Sobey, Mr. Samuel James Hayden', 0, 2, 135),
 ('SC/PARIS 2133', 15.0458, None, 'C', 0, 'Richard, Mr. Emile', 0, 2, 136),
 ('11752', 26.2833, 'D47', 'S', 1, 'Newsom, Miss. Helen Monypeny', 0, 1, 137),
 ('113803', 53.1, 'C123', 'S', 0, 'Futrelle, Mr. Jacques Heath', 1, 1, 138),
 ('7534', 9.2167, None, 'S', 0, 'Osen, Mr. Olaf Elon', 0, 3, 139),
 ('PC 17593', 79.2, 'B86', 'C', 0, 'Giglio, Mr. Victor', 0, 1, 140),
 ('2678', 15.2458, None, 'C', 0, 'Boulos, Mrs. Joseph (Sultana)', 0, 3, 141),
 ('347081', 7.75, None, 'S', 1, 'Nysten, Miss. Anna Sofia', 0, 3, 142),
 ('STON/O2. 3101279', 15.85, None, 'S', 1, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 1, 3, 143),
 ('365222', 6.75, None, 'Q', 0, 'Burke, Mr. Jeremiah', 0, 3, 144),
 ('231945', 11.5, None, 'S', 0, 'Andrew, Mr. Edgardo Samuel', 0, 2, 145),
 ('C.A. 33112', 36.75, None, 'S', 0, 'Nicholls, Mr. Joseph Charles', 1, 2, 146),
 ('350043', 7.7958, None, 'S', 1, 'Andersson, Mr. August Edvard ("Wennerstrom")', 0, 3, 147),
 ('W./C. 6608', 34.375, None, 'S', 0, 'Ford, Miss. Robina Maggie "Ruby"', 2, 3, 148),
 ('230080', 26.0, 'F2', 'S', 0, 'Navratil, Mr. Michel ("Louis M Hoffman")', 0, 2, 149),
 ('244310', 13.0, None, 'S', 0, 'Byles, Rev. Thomas Roussel Davids', 0, 2, 150),
 ('S.O.P. 1166', 12.525, None, 'S', 0, 'Bateman, Rev. Robert James', 0, 2, 151),
 ('113776', 66.6, 'C2', 'S', 1, 'Pears, Mrs. Thomas (Edith Wearne)', 1, 1, 152),
 ('A.5. 11206', 8.05, None, 'S', 0, 'Meo, Mr. Alfonzo', 0, 3, 153),
 ('A/5. 851', 14.5, None, 'S', 0, 'van Billiard, Mr. Austin Blyler', 0, 3, 154),
 ('Fa 265302', 7.3125, None, 'S', 0, 'Olsen, Mr. Ole Martin', 0, 3, 155),
 ('PC 17597', 61.3792, None, 'C', 0, 'Williams, Mr. Charles Duane', 0, 1, 156),
 ('35851', 7.7333, None, 'Q', 1, 'Gilnagh, Miss. Katherine "Katie"', 0, 3, 157),
 ('SOTON/OQ 392090', 8.05, None, 'S', 0, 'Corn, Mr. Harry', 0, 3, 158),
 ('315037', 8.6625, None, 'S', 0, 'Smiljanic, Mr. Mile', 0, 3, 159),
 ('CA. 2343', 69.55, None, 'S', 0, 'Sage, Master. Thomas Henry', 8, 3, 160),
 ('371362', 16.1, None, 'S', 0, 'Cribb, Mr. John Hatfield', 0, 3, 161),
 ('C.A. 33595', 15.75, None, 'S', 1, 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 0, 2, 162),
 ('347068', 7.775, None, 'S', 0, 'Bengtsson, Mr. John Viktor', 0, 3, 163),
 ('315093', 8.6625, None, 'S', 0, 'Calic, Mr. Jovo', 0, 3, 164),
 ('3101295', 39.6875, None, 'S', 0, 'Panula, Master. Eino Viljami', 4, 3, 165),
 ('363291', 20.525, None, 'S', 1, 'Goldsmith, Master. Frank John William "Frankie"', 0, 3, 166),
 ('113505', 55.0, 'E33', 'S', 1, 'Chibnall, Mrs. (Edith Martha Bowerman)', 0, 1, 167),
 ('347088', 27.9, None, 'S', 0, 'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 1, 3, 168),
 ('PC 17318', 25.925, None, 'S', 0, 'Baumann, Mr. John D', 0, 1, 169),
 ('1601', 56.4958, None, 'S', 0, 'Ling, Mr. Lee', 0, 3, 170),
 ('111240', 33.5, 'B19', 'S', 0, 'Van der hoef, Mr. Wyckoff', 0, 1, 171),
 ('382652', 29.125, None, 'Q', 0, 'Rice, Master. Arthur', 4, 3, 172),
 ('347742', 11.1333, None, 'S', 1, 'Johnson, Miss. Eleanor Ileen', 1, 3, 173),
 ('STON/O 2. 3101280', 7.925, None, 'S', 0, 'Sivola, Mr. Antti Wilhelm', 0, 3, 174),
 ('17764', 30.6958, 'A7', 'C', 0, 'Smith, Mr. James Clinch', 0, 1, 175),
 ('350404', 7.8542, None, 'S', 0, 'Klasen, Mr. Klas Albin', 1, 3, 176),
 ('4133', 25.4667, None, 'S', 0, 'Lefebre, Master. Henry Forbes', 3, 3, 177),
 ('PC 17595', 28.7125, 'C49', 'C', 0, 'Isham, Miss. Ann Elizabeth', 0, 1, 178),
 ('250653', 13.0, None, 'S', 0, 'Hale, Mr. Reginald', 0, 2, 179),
 ('LINE', 0.0, None, 'S', 0, 'Leonard, Mr. Lionel', 0, 3, 180),
 ('CA. 2343', 69.55, None, 'S', 0, 'Sage, Miss. Constance Gladys', 8, 3, 181),
 ('SC/PARIS 2131', 15.05, None, 'C', 0, 'Pernot, Mr. Rene', 0, 2, 182),
 ('347077', 31.3875, None, 'S', 0, 'Asplund, Master. Clarence Gustaf Hugo', 4, 3, 183),
 ('230136', 39.0, 'F4', 'S', 1, 'Becker, Master. Richard F', 2, 2, 184),
 ('315153', 22.025, None, 'S', 1, 'Kink-Heilmann, Miss. Luise Gretchen', 0, 3, 185),
 ('113767', 50.0, 'A32', 'S', 0, 'Rood, Mr. Hugh Roscoe', 0, 1, 186),
 ('370365', 15.5, None, 'Q', 1, 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 1, 3, 187),
 ('111428', 26.55, None, 'S', 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 0, 1, 188),
 ('364849', 15.5, None, 'Q', 0, 'Bourke, Mr. John', 1, 3, 189),
 ('349247', 7.8958, None, 'S', 0, 'Turcin, Mr. Stjepan', 0, 3, 190),
 ('234604', 13.0, None, 'S', 1, 'Pinsky, Mrs. (Rosa)', 0, 2, 191),
 ('28424', 13.0, None, 'S', 0, 'Carbines, Mr. William', 0, 2, 192),
 ('350046', 7.8542, None, 'S', 1, 'Andersen-Jensen, Miss. Carla Christine Nielsine', 1, 3, 193),
 ('230080', 26.0, 'F2', 'S', 1, 'Navratil, Master. Michel M', 1, 2, 194),
 ('PC 17610', 27.7208, 'B4', 'C', 1, 'Brown, Mrs. James Joseph (Margaret Tobin)', 0, 1, 195),
 ('PC 17569', 146.5208, 'B80', 'C', 1, 'Lurette, Miss. Elise', 0, 1, 196),
 ('368703', 7.75, None, 'Q', 0, 'Mernagh, Mr. Robert', 0, 3, 197),
 ('4579', 8.4042, None, 'S', 0, 'Olsen, Mr. Karl Siegwart Andreas', 0, 3, 198),
 ('370370', 7.75, None, 'Q', 1, 'Madigan, Miss. Margaret "Maggie"', 0, 3, 199),
 ('248747', 13.0, None, 'S', 0, 'Yrois, Miss. Henriette ("Mrs Harbeck")', 0, 2, 200),
 ('345770', 9.5, None, 'S', 0, 'Vande Walle, Mr. Nestor Cyriel', 0, 3, 201),
 ('CA. 2343', 69.55, None, 'S', 0, 'Sage, Mr. Frederick', 8, 3, 202),
 ('3101264', 6.4958, None, 'S', 0, 'Johanson, Mr. Jakob Alfred', 0, 3, 203),
 ('2628', 7.225, None, 'C', 0, 'Youseff, Mr. Gerious', 0, 3, 204),
 ('A/5 3540', 8.05, None, 'S', 1, 'Cohen, Mr. Gurshon "Gus"', 0, 3, 205),
 ('347054', 10.4625, 'G6', 'S', 0, 'Strom, Miss. Telma Matilda', 0, 3, 206),
 ('3101278', 15.85, None, 'S', 0, 'Backstrom, Mr. Karl Alfred', 1, 3, 207),
 ('2699', 18.7875, None, 'C', 1, 'Albimona, Mr. Nassef Cassem', 0, 3, 208),
 ('367231', 7.75, None, 'Q', 1, 'Carr, Miss. Helen "Ellen"', 0, 3, 209),
 ('112277', 31.0, 'A31', 'C', 1, 'Blank, Mr. Henry', 0, 1, 210),
 ('SOTON/O.Q. 3101311', 7.05, None, 'S', 0, 'Ali, Mr. Ahmed', 0, 3, 211),
 ('F.C.C. 13528', 21.0, None, 'S', 1, 'Cameron, Miss. Clear Annie', 0, 2, 212),
 ('A/5 21174', 7.25, None, 'S', 0, 'Perkin, Mr. John Henry', 0, 3, 213),
 ('250646', 13.0, None, 'S', 0, 'Givard, Mr. Hans Kristensen', 0, 2, 214),
 ('367229', 7.75, None, 'Q', 0, 'Kiernan, Mr. Philip', 1, 3, 215),
 ('35273', 113.275, 'D36', 'C', 1, 'Newell, Miss. Madeleine', 1, 1, 216),
 ('STON/O2. 3101283', 7.925, None, 'S', 1, 'Honkanen, Miss. Eliina', 0, 3, 217),
 ('243847', 27.0, None, 'S', 0, 'Jacobsohn, Mr. Sidney Samuel', 1, 2, 218),
 ('11813', 76.2917, 'D15', 'C', 1, 'Bazzani, Miss. Albina', 0, 1, 219),
 ('W/C 14208', 10.5, None, 'S', 0, 'Harris, Mr. Walter', 0, 2, 220),
 ('SOTON/OQ 392089', 8.05, None, 'S', 1, 'Sunderland, Mr. Victor Francis', 0, 3, 221),
 ('220367', 13.0, None, 'S', 0, 'Bracken, Mr. James H', 0, 2, 222),
 ('21440', 8.05, None, 'S', 0, 'Green, Mr. George Henry', 0, 3, 223),
 ('349234', 7.8958, None, 'S', 0, 'Nenkoff, Mr. Christo', 0, 3, 224),
 ('19943', 90.0, 'C93', 'S', 1, 'Hoyt, Mr. Frederick Maxfield', 1, 1, 225),
 ('PP 4348', 9.35, None, 'S', 0, 'Berglund, Mr. Karl Ivar Sven', 0, 3, 226),
 ('SW/PP 751', 10.5, None, 'S', 1, 'Mellors, Mr. William John', 0, 2, 227),
 ('A/5 21173', 7.25, None, 'S', 0, 'Lovell, Mr. John Hall ("Henry")', 0, 3, 228),
 ('236171', 13.0, None, 'S', 0, 'Fahlstrom, Mr. Arne Jonas', 0, 2, 229),
 ('4133', 25.4667, None, 'S', 0, 'Lefebre, Miss. Mathilde', 3, 3, 230),
 ('36973', 83.475, 'C83', 'S', 1, 'Harris, Mrs. Henry Birkhardt (Irene Wallach)', 1, 1, 231),
 ('347067', 7.775, None, 'S', 0, 'Larsson, Mr. Bengt Edvin', 0, 3, 232),
 ('237442', 13.5, None, 'S', 0, 'Sjostedt, Mr. Ernst Adolf', 0, 2, 233),
 ('347077', 31.3875, None, 'S', 1, 'Asplund, Miss. Lillian Gertrud', 4, 3, 234),
 ('C.A. 29566', 10.5, None, 'S', 0, 'Leyson, Mr. Robert William Norman', 0, 2, 235),
 ('W./C. 6609', 7.55, None, 'S', 0, 'Harknett, Miss. Alice Phoebe', 0, 3, 236),
 ('26707', 26.0, None, 'S', 0, 'Hold, Mr. Stephen', 1, 2, 237),
 ('C.A. 31921', 26.25, None, 'S', 1, 'Collyer, Miss. Marjorie "Lottie"', 0, 2, 238),
 ('28665', 10.5, None, 'S', 0, 'Pengelly, Mr. Frederick William', 0, 2, 239),
 ('SCO/W 1585', 12.275, None, 'S', 0, 'Hunt, Mr. George Henry', 0, 2, 240),
 ('2665', 14.4542, None, 'C', 0, 'Zabour, Miss. Thamine', 1, 3, 241),
 ('367230', 15.5, None, 'Q', 1, 'Murphy, Miss. Katherine "Kate"', 1, 3, 242),
 ('W./C. 14263', 10.5, None, 'S', 0, 'Coleridge, Mr. Reginald Charles', 0, 2, 243),
 ('STON/O 2. 3101275', 7.125, None, 'S', 0, 'Maenpaa, Mr. Matti Alexanteri', 0, 3, 244),
 ('2694', 7.225, None, 'C', 0, 'Attalah, Mr. Sleiman', 0, 3, 245),
 ('19928', 90.0, 'C78', 'Q', 0, 'Minahan, Dr. William Edward', 2, 1, 246),
 ('347071', 7.775, None, 'S', 0, 'Lindahl, Miss. Agda Thorilda Viktoria', 0, 3, 247),
 ('250649', 14.5, None, 'S', 1, 'Hamalainen, Mrs. William (Anna)', 0, 2, 248),
 ('11751', 52.5542, 'D35', 'S', 1, 'Beckwith, Mr. Richard Leonard', 1, 1, 249),
 ('244252', 26.0, None, 'S', 0, 'Carter, Rev. Ernest Courtenay', 1, 2, 250),
 ('362316', 7.25, None, 'S', 0, 'Reed, Mr. James George', 0, 3, 251),
 ('347054', 10.4625, 'G6', 'S', 0, 'Strom, Mrs. Wilhelm (Elna Matilda Persson)', 1, 3, 252),
 ('113514', 26.55, 'C87', 'S', 0, 'Stead, Mr. William Thomas', 0, 1, 253),
 ('A/5. 3336', 16.1, None, 'S', 0, 'Lobb, Mr. William Arthur', 1, 3, 254),
 ('370129', 20.2125, None, 'S', 0, 'Rosblom, Mrs. Viktor (Helena Wilhelmina)', 0, 3, 255),
 ('2650', 15.2458, None, 'C', 1, 'Touma, Mrs. Darwis (Hanne Youssef Razi)', 0, 3, 256),
 ('PC 17585', 79.2, None, 'C', 1, 'Thorne, Mrs. Gertrude Maybelle', 0, 1, 257),
 ('110152', 86.5, 'B77', 'S', 1, 'Cherry, Miss. Gladys', 0, 1, 258),
 ('PC 17755', 512.3292, None, 'C', 1, 'Ward, Miss. Anna', 0, 1, 259),

## PHASE 3 ##

Objectifs :
-Créer des requetes afin d'interroger notre base de donnée.
-Répondre aux requetes imposées.

Création de requete afin d'intérroger la base de donnée:

-Afficher les noms des passagers présents à bord du titanic
-Quels sont les noms des personnes n'ayant pas survecu à bord du titanic
-Afficher toutes les informations concernant les numéros de cabines qui n'ont pas été fourni
-Quels sont les passagers qui ont embarqués à Cherbourg

In [212]:
%%sql
SELECT NAME FROM Passagers;

 * postgresql://oceane:***@localhost/postgres
891 rows affected.

[('Braund, Mr. Owen Harris',),
 ('Cumings, Mrs. John Bradley (Florence Briggs Thayer)',),
 ('Heikkinen, Miss. Laina',),
 ('Futrelle, Mrs. Jacques Heath (Lily May Peel)',),
 ('Allen, Mr. William Henry',),
 ('Moran, Mr. James',),
 ('McCarthy, Mr. Timothy J',),
 ('Palsson, Master. Gosta Leonard',),
 ('Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',),
 ('Nasser, Mrs. Nicholas (Adele Achem)',),
 ('Sandstrom, Miss. Marguerite Rut',),
 ('Bonnell, Miss. Elizabeth',),
 ('Saundercock, Mr. William Henry',),
 ('Andersson, Mr. Anders Johan',),
 ('Vestrom, Miss. Hulda Amanda Adolfina',),
 ('Hewlett, Mrs. (Mary D Kingcome) ',),
 ('Rice, Master. Eugene',),
 ('Williams, Mr. Charles Eugene',),
 ('Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',),
 ('Masselmani, Mrs. Fatima',),
 ('Fynney, Mr. Joseph J',),
 ('Beesley, Mr. Lawrence',),
 ('McGowan, Miss. Anna "Annie"',),
 ('Sloper, Mr. William Thompson',),
 ('Palsson, Miss. Torborg Danira',),
 ('Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',),
 ('Emir, Mr. Farred Chehab',),
 ('Fortune, Mr. Charles Alexander',),
 ('O\'Dwyer, Miss. Ellen "Nellie"',),
 ('Todoroff, Mr. Lalio',),
 ('Uruchurtu, Don. Manuel E',),
 ('Spencer, Mrs. William Augustus (Marie Eugenie)',),
 ('Glynn, Miss. Mary Agatha',),
 ('Wheadon, Mr. Edward H',),
 ('Meyer, Mr. Edgar Joseph',),
 ('Holverson, Mr. Alexander Oskar',),
 ('Mamee, Mr. Hanna',),
 ('Cann, Mr. Ernest Charles',),
 ('Vander Planke, Miss. Augusta Maria',),
 ('Nicola-Yarred, Miss. Jamila',),
 ('Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',),
 ('Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',),
 ('Kraeff, Mr. Theodor',),
 ('Laroche, Miss. Simonne Marie Anne Andree',),
 ('Devaney, Miss. Margaret Delia',),
 ('Rogers, Mr. William John',),
 ('Lennon, Mr. Denis',),
 ("O'Driscoll, Miss. Bridget",),
 ('Samaan, Mr. Youssef',),
 ('Arnold-Franchi, Mrs. Josef (Josefine Franchi)',),
 ('Panula, Master. Juha Niilo',),
 ('Nosworthy, Mr. Richard Cater',),
 ('Harper, Mrs. Henry Sleeper (Myna Haxtun)',),
 ('Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',),
 ('Ostby, Mr. Engelhart Cornelius',),
 ('Woolner, Mr. Hugh',),
 ('Rugg, Miss. Emily',),
 ('Novel, Mr. Mansouer',),
 ('West, Miss. Constance Mirium',),
 ('Goodwin, Master. William Frederick',),
 ('Sirayanian, Mr. Orsen',),
 ('Icard, Miss. Amelie',),
 ('Harris, Mr. Henry Birkhardt',),
 ('Skoog, Master. Harald',),
 ('Stewart, Mr. Albert A',),
 ('Moubarek, Master. Gerios',),
 ('Nye, Mrs. (Elizabeth Ramell)',),
 ('Crease, Mr. Ernest James',),
 ('Andersson, Miss. Erna Alexandra',),
 ('Kink, Mr. Vincenz',),
 ('Jenkin, Mr. Stephen Curnow',),
 ('Goodwin, Miss. Lillian Amy',),
 ('Hood, Mr. Ambrose Jr',),
 ('Chronopoulos, Mr. Apostolos',),
 ('Bing, Mr. Lee',),
 ('Moen, Mr. Sigurd Hansen',),
 ('Staneff, Mr. Ivan',),
 ('Moutal, Mr. Rahamin Haim',),
 ('Caldwell, Master. Alden Gates',),
 ('Dowdell, Miss. Elizabeth',),
 ('Waelens, Mr. Achille',),
 ('Sheerlinck, Mr. Jan Baptist',),
 ('McDermott, Miss. Brigdet Delia',),
 ('Carrau, Mr. Francisco M',),
 ('Ilett, Miss. Bertha',),
 ('Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',),
 ('Ford, Mr. William Neal',),
 ('Slocovski, Mr. Selman Francis',),
 ('Fortune, Miss. Mabel Helen',),
 ('Celotti, Mr. Francesco',),
 ('Christmann, Mr. Emil',),
 ('Andreasson, Mr. Paul Edvin',),
 ('Chaffee, Mr. Herbert Fuller',),
 ('Dean, Mr. Bertram Frank',),
 ('Coxon, Mr. Daniel',),
 ('Shorney, Mr. Charles Joseph',),
 ('Goldschmidt, Mr. George B',),
 ('Greenfield, Mr. William Bertram',),
 ('Doling, Mrs. John T (Ada Julia Bone)',),
 ('Kantor, Mr. Sinai',),
 ('Petranec, Miss. Matilda',),
 ('Petroff, Mr. Pastcho ("Pentcho")',),
 ('White, Mr. Richard Frasar',),
 ('Johansson, Mr. Gustaf Joel',),
 ('Gustafsson, Mr. Anders Vilhelm',),
 ('Mionoff, Mr. Stoytcho',),
 ('Salkjelsvik, Miss. Anna Kristine',),
 ('Moss, Mr. Albert Johan',),
 ('Rekic, Mr. Tido',),
 ('Moran, Miss. Bertha',),
 ('Porter, Mr. Walter Chamberlain',),
 ('Zabour, Miss. Hileni',),
 ('Barton, Mr. David John',),
 ('Jussila, Miss. Katriina',),
 ('Attalah, Miss. Malake',),
 ('Pekoniemi, Mr. Edvard',),
 ('Connors, Mr. Patrick',),
 ('Turpin, Mr. William John Robert',),
 ('Baxter, Mr. Quigg Edmond',),
 ('Andersson, Miss. Ellis Anna Maria',),
 ('Hickman, Mr. Stanley George',),
 ('Moore, Mr. Leonard Charles',),
 ('Nasser, Mr. Nicholas',),
 ('Webber, Miss. Susan',),
 ('White, Mr. Percival Wayland',),
 ('Nicola-Yarred, Master. Elias',),
 ('McMahon, Mr. Martin',),
 ('Madsen, Mr. Fridtjof Arne',),
 ('Peter, Miss. Anna',),
 ('Ekstrom, Mr. Johan',),
 ('Drazenoic, Mr. Jozef',),
 ('Coelho, Mr. Domingos Fernandeo',),
 ('Robins, Mrs. Alexander A (Grace Charity Laury)',),
 ('Weisz, Mrs. Leopold (Mathilde Francoise Pede)',),
 ('Sobey, Mr. Samuel James Hayden',),
 ('Richard, Mr. Emile',),
 ('Newsom, Miss. Helen Monypeny',),
 ('Futrelle, Mr. Jacques Heath',),
 ('Osen, Mr. Olaf Elon',),
 ('Giglio, Mr. Victor',),
 ('Boulos, Mrs. Joseph (Sultana)',),
 ('Nysten, Miss. Anna Sofia',),
 ('Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',),
 ('Burke, Mr. Jeremiah',),
 ('Andrew, Mr. Edgardo Samuel',),
 ('Nicholls, Mr. Joseph Charles',),
 ('Andersson, Mr. August Edvard ("Wennerstrom")',),
 ('Ford, Miss. Robina Maggie "Ruby"',),
 ('Navratil, Mr. Michel ("Louis M Hoffman")',),
 ('Byles, Rev. Thomas Roussel Davids',),
 ('Bateman, Rev. Robert James',),
 ('Pears, Mrs. Thomas (Edith Wearne)',),
 ('Meo, Mr. Alfonzo',),
 ('van Billiard, Mr. Austin Blyler',),
 ('Olsen, Mr. Ole Martin',),
 ('Williams, Mr. Charles Duane',),
 ('Gilnagh, Miss. Katherine "Katie"',),
 ('Corn, Mr. Harry',),
 ('Smiljanic, Mr. Mile',),
 ('Sage, Master. Thomas Henry',),
 ('Cribb, Mr. John Hatfield',),
 ('Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',),
 ('Bengtsson, Mr. John Viktor',),
 ('Calic, Mr. Jovo',),
 ('Panula, Master. Eino Viljami',),
 ('Goldsmith, Master. Frank John William "Frankie"',),
 ('Chibnall, Mrs. (Edith Martha Bowerman)',),
 ('Skoog, Mrs. William (Anna Bernhardina Karlsson)',),
 ('Baumann, Mr. John D',),
 ('Ling, Mr. Lee',),
 ('Van der hoef, Mr. Wyckoff',),
 ('Rice, Master. Arthur',),
 ('Johnson, Miss. Eleanor Ileen',),
 ('Sivola, Mr. Antti Wilhelm',),
 ('Smith, Mr. James Clinch',),
 ('Klasen, Mr. Klas Albin',),
 ('Lefebre, Master. Henry Forbes',),
 ('Isham, Miss. Ann Elizabeth',),
 ('Hale, Mr. Reginald',),
 ('Leonard, Mr. Lionel',),
 ('Sage, Miss. Constance Gladys',),
 ('Pernot, Mr. Rene',),
 ('Asplund, Master. Clarence Gustaf Hugo',),
 ('Becker, Master. Richard F',),
 ('Kink-Heilmann, Miss. Luise Gretchen',),
 ('Rood, Mr. Hugh Roscoe',),
 ('O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)',),
 ('Romaine, Mr. Charles Hallace ("Mr C Rolmane")',),
 ('Bourke, Mr. John',),
 ('Turcin, Mr. Stjepan',),
 ('Pinsky, Mrs. (Rosa)',),
 ('Carbines, Mr. William',),
 ('Andersen-Jensen, Miss. Carla Christine Nielsine',),
 ('Navratil, Master. Michel M',),
 ('Brown, Mrs. James Joseph (Margaret Tobin)',),
 ('Lurette, Miss. Elise',),
 ('Mernagh, Mr. Robert',),
 ('Olsen, Mr. Karl Siegwart Andreas',),
 ('Madigan, Miss. Margaret "Maggie"',),
 ('Yrois, Miss. Henriette ("Mrs Harbeck")',),
 ('Vande Walle, Mr. Nestor Cyriel',),
 ('Sage, Mr. Frederick',),
 ('Johanson, Mr. Jakob Alfred',),
 ('Youseff, Mr. Gerious',),
 ('Cohen, Mr. Gurshon "Gus"',),
 ('Strom, Miss. Telma Matilda',),
 ('Backstrom, Mr. Karl Alfred',),
 ('Albimona, Mr. Nassef Cassem',),
 ('Carr, Miss. Helen "Ellen"',),
 ('Blank, Mr. Henry',),
 ('Ali, Mr. Ahmed',),
 ('Cameron, Miss. Clear Annie',),
 ('Perkin, Mr. John Henry',),
 ('Givard, Mr. Hans Kristensen',),
 ('Kiernan, Mr. Philip',),
 ('Newell, Miss. Madeleine',),
 ('Honkanen, Miss. Eliina',),
 ('Jacobsohn, Mr. Sidney Samuel',),
 ('Bazzani, Miss. Albina',),
 ('Harris, Mr. Walter',),
 ('Sunderland, Mr. Victor Francis',),
 ('Bracken, Mr. James H',),
 ('Green, Mr. George Henry',),
 ('Nenkoff, Mr. Christo',),
 ('Hoyt, Mr. Frederick Maxfield',),
 ('Berglund, Mr. Karl Ivar Sven',),
 ('Mellors, Mr. William John',),
 ('Lovell, Mr. John Hall ("Henry")',),
 ('Fahlstrom, Mr. Arne Jonas',),
 ('Lefebre, Miss. Mathilde',),
 ('Harris, Mrs. Henry Birkhardt (Irene Wallach)',),
 ('Larsson, Mr. Bengt Edvin',),
 ('Sjostedt, Mr. Ernst Adolf',),
 ('Asplund, Miss. Lillian Gertrud',),
 ('Leyson, Mr. Robert William Norman',),
 ('Harknett, Miss. Alice Phoebe',),
 ('Hold, Mr. Stephen',),
 ('Collyer, Miss. Marjorie "Lottie"',),
 ('Pengelly, Mr. Frederick William',),
 ('Hunt, Mr. George Henry',),
 ('Zabour, Miss. Thamine',),
 ('Murphy, Miss. Katherine "Kate"',),
 ('Coleridge, Mr. Reginald Charles',),
 ('Maenpaa, Mr. Matti Alexanteri',),
 ('Attalah, Mr. Sleiman',),
 ('Minahan, Dr. William Edward',),
 ('Lindahl, Miss. Agda Thorilda Viktoria',),
 ('Hamalainen, Mrs. William (Anna)',),
 ('Beckwith, Mr. Richard Leonard',),
 ('Carter, Rev. Ernest Courtenay',),
 ('Reed, Mr. James George',),
 ('Strom, Mrs. Wilhelm (Elna Matilda Persson)',),
 ('Stead, Mr. William Thomas',),
 ('Lobb, Mr. William Arthur',),
 ('Rosblom, Mrs. Viktor (Helena Wilhelmina)',),
 ('Touma, Mrs. Darwis (Hanne Youssef Razi)',),
 ('Thorne, Mrs. Gertrude Maybelle',),
 ('Cherry, Miss. Gladys',),
 ('Ward, Miss. Anna',),
 ('Parrish, Mrs. (Lutie Davis)',),
 ('Smith, Mr. Thomas',),
 ('Asplund, Master. Edvin Rojj Felix',),
 ('Taussig, Mr. Emil',),
 ('Harrison, Mr. William',),
 ('Henry, Miss. Delia',),
 ('Reeves, Mr. David',),
 ('Panula, Mr. Ernesti Arvid',),
 ('Persson, Mr. Ernst Ulrik',),
 ('Graham, Mrs. William Thompson (Edith Junkins)',),
 ('Bissette, Miss. Amelia',),
 ('Cairns, Mr. Alexander',),
 ('Tornquist, Mr. William Henry',),
 ('Mellinger, Mrs. (Elizabeth Anne Maidment)',),
 ('Natsch, Mr. Charles H',),
 ('Healy, Miss. Hanora "Nora"',),
 ('Andrews, Miss. Kornelia Theodosia',),
 ('Lindblom, Miss. Augusta Charlotta',),
 ('Parkes, Mr. Francis "Frank"',),
 ('Rice, Master. Eric',),
 ('Abbott, Mrs. Stanton (Rosa Hunt)',),
 ('Duane, Mr. Frank',),
 ('Olsson, Mr. Nils Johan Goransson',),
 ('de Pelsmaeker, Mr. Alfons',),
 ('Dorking, Mr. Edward Arthur',),
 ('Smith, Mr. Richard William',),
 ('Stankovic, Mr. Ivan',),
 ('de Mulder, Mr. Theodore',),
 ('Naidenoff, Mr. Penko',),
 ('Hosono, Mr. Masabumi',),
 ('Connolly, Miss. Kate',),
 ('Barber, Miss. Ellen "Nellie"',),
 ('Bishop, Mrs. Dickinson H (Helen Walton)',),
 ('Levy, Mr. Rene Jacques',),
 ('Haas, Miss. Aloisia',),
 ('Mineff, Mr. Ivan',),
 ('Lewy, Mr. Ervin G',),
 ('Hanna, Mr. Mansour',),
 ('Allison, Miss. Helen Loraine',),
 ('Saalfeld, Mr. Adolphe',),
 ('Baxter, Mrs. James (Helene DeLaudeniere Chaput)',),
 ('Kelly, Miss. Anna Katherine "Annie Kate"',),
 ('McCoy, Mr. Bernard',),
 ('Johnson, Mr. William Cahoone Jr',),
 ('Keane, Miss. Nora A',),
 ('Williams, Mr. Howard Hugh "Harry"',),
 ('Allison, Master. Hudson Trevor',),
 ('Fleming, Miss. Margaret',),
 ('Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',),
 ('Abelson, Mr. Samuel',),
 ('Francatelli, Miss. Laura Mabel',),
 ('Hays, Miss. Margaret Bechstein',),
 ('Ryerson, Miss. Emily Borie',),
 ('Lahtinen, Mrs. William (Anna Sylfven)',),
 ('Hendekovic, Mr. Ignjac',),
 ('Hart, Mr. Benjamin',),
 ('Nilsson, Miss. Helmina Josefina',),
 ('Kantor, Mrs. Sinai (Miriam Sternin)',),
 ('Moraweck, Dr. Ernest',),
 ('Wick, Miss. Mary Natalie',),
 ('Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',),
 ('Dennis, Mr. Samuel',),
 ('Danoff, Mr. Yoto',),
 ('Slayter, Miss. Hilda Mary',),
 ('Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',),
 ('Sage, Mr. George John Jr',),
 ('Young, Miss. Marie Grice',),
 ('Nysveen, Mr. Johan Hansen',),
 ('Ball, Mrs. (Ada E Hall)',),
 ('Goldsmith, Mrs. Frank John (Emily Alice Brown)',),
 ('Hippach, Miss. Jean Gertrude',),
 ('McCoy, Miss. Agnes',),
 ('Partner, Mr. Austen',),
 ('Graham, Mr. George Edward',),
 ('Vander Planke, Mr. Leo Edmondus',),
 ('Frauenthal, Mrs. Henry William (Clara Heinsheimer)',),
 ('Denkoff, Mr. Mitto',),
 ('Pears, Mr. Thomas Clinton',),
 ('Burns, Miss. Elizabeth Margaret',),
 ('Dahl, Mr. Karl Edwart',),
 ('Blackwell, Mr. Stephen Weart',),
 ('Navratil, Master. Edmond Roger',),
 ('Fortune, Miss. Alice Elizabeth',),
 ('Collander, Mr. Erik Gustaf',),
 ('Sedgwick, Mr. Charles Frederick Waddington',),
 ('Fox, Mr. Stanley Hubert',),
 ('Brown, Miss. Amelia "Mildred"',),
 ('Smith, Miss. Marion Elsie',),
 ('Davison, Mrs. Thomas Henry (Mary E Finck)',),
 ('Coutts, Master. William Loch "William"',),
 ('Dimic, Mr. Jovan',),
 ('Odahl, Mr. Nils Martin',),
 ('Williams-Lambert, Mr. Fletcher Fellows',),
 ('Elias, Mr. Tannous',),
 ('Arnold-Franchi, Mr. Josef',),
 ('Yousif, Mr. Wazli',),
 ('Vanden Steen, Mr. Leo Peter',),
 ('Bowerman, Miss. Elsie Edith',),
 ('Funk, Miss. Annie Clemmer',),
 ('McGovern, Miss. Mary',),
 ('Mockler, Miss. Helen Mary "Ellie"',),
 ('Skoog, Mr. Wilhelm',),
 ('del Carlo, Mr. Sebastiano',),
 ('Barbara, Mrs. (Catherine David)',),
 ('Asim, Mr. Adola',),
 ("O'Brien, Mr. Thomas",),
 ('Adahl, Mr. Mauritz Nils Martin',),
 ('Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',),
 ('Moussa, Mrs. (Mantoura Boulos)',),
 ('Jermyn, Miss. Annie',),
 ('Aubart, Mme. Leontine Pauline',),
 ('Harder, Mr. George Achilles',),
 ('Wiklund, Mr. Jakob Alfred',),
 ('Beavan, Mr. William Thomas',),
 ('Ringhini, Mr. Sante',),
 ('Palsson, Miss. Stina Viola',),
 ('Meyer, Mrs. Edgar Joseph (Leila Saks)',),
 ('Landergren, Miss. Aurora Adelia',),
 ('Widener, Mr. Harry Elkins',),
 ('Betros, Mr. Tannous',),
 ('Gustafsson, Mr. Karl Gideon',),
 ('Bidois, Miss. Rosalie',),
 ('Nakid, Miss. Maria ("Mary")',),
 ('Tikkanen, Mr. Juho',),
 ('Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',),
 ('Plotcharsky, Mr. Vasil',),
 ('Davies, Mr. Charles Henry',),
 ('Goodwin, Master. Sidney Leonard',),
 ('Buss, Miss. Kate',),
 ('Sadlier, Mr. Matthew',),
 ('Lehmann, Miss. Bertha',),
 ('Carter, Mr. William Ernest',),
 ('Jansson, Mr. Carl Olof',),
 ('Gustafsson, Mr. Johan Birger',),
 ('Newell, Miss. Marjorie',),
 ('Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',),
 ('Johansson, Mr. Erik',),
 ('Olsson, Miss. Elina',),
 ('McKane, Mr. Peter David',),
 ('Pain, Dr. Alfred',),
 ('Trout, Mrs. William H (Jessie L)',),
 ('Niskanen, Mr. Juha',),
 ('Adams, Mr. John',),
 ('Jussila, Miss. Mari Aina',),
 ('Hakkarainen, Mr. Pekka Pietari',),
 ('Oreskovic, Miss. Marija',),
 ('Gale, Mr. Shadrach',),
 ('Widegren, Mr. Carl/Charles Peter',),
 ('Richards, Master. William Rowe',),
 ('Birkeland, Mr. Hans Martin Monsen',),
 ('Lefebre, Miss. Ida',),
 ('Sdycoff, Mr. Todor',),
 ('Hart, Mr. Henry',),
 ('Minahan, Miss. Daisy E',),
 ('Cunningham, Mr. Alfred Fleming',),
 ('Sundman, Mr. Johan Julian',),
 ('Meek, Mrs. Thomas (Annie Louise Rowley)',),
 ('Drew, Mrs. James Vivian (Lulu Thorne Christian)',),
 ('Silven, Miss. Lyyli Karoliina',),
 ('Matthews, Mr. William John',),
 ('Van Impe, Miss. Catharina',),
 ('Gheorgheff, Mr. Stanio',),
 ('Charters, Mr. David',),
 ('Zimmerman, Mr. Leo',),
 ('Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',),
 ('Rosblom, Mr. Viktor Richard',),
 ('Wiseman, Mr. Phillippe',),
 ('Clarke, Mrs. Charles V (Ada Maria Winfield)',),
 ('Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")',),
 ('Flynn, Mr. James',),
 ('Pickard, Mr. Berk (Berk Trembisky)',),
 ('Bjornstrom-Steffansson, Mr. Mauritz Hakan',),
 ('Thorneycroft, Mrs. Percival (Florence Kate White)',),
 ('Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',),
 ('Kallio, Mr. Nikolai Erland',),
 ('Silvey, Mr. William Baird',),
 ('Carter, Miss. Lucile Polk',),
 ('Ford, Miss. Doolina Margaret "Daisy"',),
 ('Richards, Mrs. Sidney (Emily Hocking)',),
 ('Fortune, Mr. Mark',),
 ('Kvillner, Mr. Johan Henrik Johannesson',),
 ('Hart, Mrs. Benjamin (Esther Ada Bloomfield)',),
 ('Hampe, Mr. Leon',),
 ('Petterson, Mr. Johan Emil',),
 ('Reynaldo, Ms. Encarnacion',),
 ('Johannesen-Bratthammer, Mr. Bernt',),
 ('Dodge, Master. Washington',),
 ('Mellinger, Miss. Madeleine Violet',),
 ('Seward, Mr. Frederic Kimber',),
 ('Baclini, Miss. Marie Catherine',),
 ('Peuchen, Major. Arthur Godfrey',),
 ('West, Mr. Edwy Arthur',),
 ('Hagland, Mr. Ingvald Olai Olsen',),
 ('Foreman, Mr. Benjamin Laventall',),
 ('Goldenberg, Mr. Samuel L',),
 ('Peduzzi, Mr. Joseph',),
 ('Jalsevac, Mr. Ivan',),
 ('Millet, Mr. Francis Davis',),
 ('Kenyon, Mrs. Frederick R (Marion)',),
 ('Toomey, Miss. Ellen',),
 ("O'Connor, Mr. Maurice",),
 ('Anderson, Mr. Harry',),
 ('Morley, Mr. William',),
 ('Gee, Mr. Arthur H',),
 ('Milling, Mr. Jacob Christian',),
 ('Maisner, Mr. Simon',),
 ('Goncalves, Mr. Manuel Estanslas',),
 ('Campbell, Mr. William',),
 ('Smart, Mr. John Montgomery',),
 ('Scanlan, Mr. James',),
 ('Baclini, Miss. Helene Barbara',),
 ('Keefe, Mr. Arthur',),
 ('Cacic, Mr. Luka',),
 ('West, Mrs. Edwy Arthur (Ada Mary Worth)',),
 ('Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',),
 ('Strandberg, Miss. Ida Sofia',),
 ('Clifford, Mr. George Quincy',),
 ('Renouf, Mr. Peter Henry',),
 ('Braund, Mr. Lewis Richard',),
 ('Karlsson, Mr. Nils August',),
 ('Hirvonen, Miss. Hildur E',),
 ('Goodwin, Master. Harold Victor',),
 ('Frost, Mr. Anthony Wood "Archie"',),
 ('Rouse, Mr. Richard Henry',),
 ('Turkula, Mrs. (Hedwig)',),
 ('Bishop, Mr. Dickinson H',),
 ('Lefebre, Miss. Jeannie',),
 ('Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',),
 ('Kent, Mr. Edward Austin',),
 ('Somerton, Mr. Francis William',),
 ('Coutts, Master. Eden Leslie "Neville"',),
 ('Hagland, Mr. Konrad Mathias Reiersen',),
 ('Windelov, Mr. Einar',),
 ('Molson, Mr. Harry Markland',),
 ('Artagaveytia, Mr. Ramon',),
 ('Stanley, Mr. Edward Roland',),
 ('Yousseff, Mr. Gerious',),
 ('Eustis, Miss. Elizabeth Mussey',),
 ('Shellard, Mr. Frederick William',),
 ('Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',),
 ('Svensson, Mr. Olof',),
 ('Calic, Mr. Petar',),
 ('Canavan, Miss. Mary',),
 ("O'Sullivan, Miss. Bridget Mary",),
 ('Laitinen, Miss. Kristina Sofia',),
 ('Maioni, Miss. Roberta',),
 ('Penasco y Castellana, Mr. Victor de Satode',),
 ('Quick, Mrs. Frederick Charles (Jane Richards)',),
 ('Bradley, Mr. George ("George Arthur Brayton")',),
 ('Olsen, Mr. Henry Margido',),
 ('Lang, Mr. Fang',),
 ('Daly, Mr. Eugene Patrick',),
 ('Webber, Mr. James',),
 ('McGough, Mr. James Robert',),
 ('Rothschild, Mrs. Martin (Elizabeth L. Barrett)',),
 ('Coleff, Mr. Satio',),
 ('Walker, Mr. William Anderson',),
 ('Lemore, Mrs. (Amelia Milley)',),
 ('Ryan, Mr. Patrick',),
 ('Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',),
 ('Pavlovic, Mr. Stefo',),
 ('Perreault, Miss. Anne',),
 ('Vovk, Mr. Janko',),
 ('Lahoud, Mr. Sarkis',),
 ('Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',),
 ('Kassem, Mr. Fared',),
 ('Farrell, Mr. James',),
 ('Ridsdale, Miss. Lucy',),
 ('Farthing, Mr. John',),
 ('Salonen, Mr. Johan Werner',),
 ('Hocking, Mr. Richard George',),
 ('Quick, Miss. Phyllis May',),
 ('Toufik, Mr. Nakli',),
 ('Elias, Mr. Joseph Jr',),
 ('Peter, Mrs. Catherine (Catherine Rizk)',),
 ('Cacic, Miss. Marija',),
 ('Hart, Miss. Eva Miriam',),
 ('Butt, Major. Archibald Willingham',),
 ('LeRoy, Miss. Bertha',),
 ('Risien, Mr. Samuel Beard',),
 ('Frolicher, Miss. Hedwig Margaritha',),
 ('Crosby, Miss. Harriet R',),
 ('Andersson, Miss. Ingeborg Constanzia',),
 ('Andersson, Miss. Sigrid Elisabeth',),
 ('Beane, Mr. Edward',),
 ('Douglas, Mr. Walter Donald',),
 ('Nicholson, Mr. Arthur Ernest',),
 ('Beane, Mrs. Edward (Ethel Clarke)',),
 ('Padro y Manent, Mr. Julian',),
 ('Goldsmith, Mr. Frank John',),
 ('Davies, Master. John Morgan Jr',),
 ('Thayer, Mr. John Borland Jr',),
 ('Sharp, Mr. Percival James R',),
 ("O'Brien, Mr. Timothy",),
 ('Leeni, Mr. Fahim ("Philip Zenni")',),
 ('Ohman, Miss. Velin',),
 ('Wright, Mr. George',),
 ('Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',),
 ('Robbins, Mr. Victor',),
 ('Taussig, Mrs. Emil (Tillie Mandelbaum)',),
 ('de Messemaeker, Mrs. Guillaume Joseph (Emma)',),
 ('Morrow, Mr. Thomas Rowan',),
 ('Sivic, Mr. Husein',),
 ('Norman, Mr. Robert Douglas',),
 ('Simmons, Mr. John',),
 ('Meanwell, Miss. (Marion Ogden)',),
 ('Davies, Mr. Alfred J',),
 ('Stoytcheff, Mr. Ilia',),
 ('Palsson, Mrs. Nils (Alma Cornelia Berglund)',),
 ('Doharr, Mr. Tannous',),
 ('Jonsson, Mr. Carl',),

In [211]:
%%sql 
SELECT Name FROM Passagers where Survived='0';

 * postgresql://oceane:***@localhost/postgres
549 rows affected.

[('Braund, Mr. Owen Harris',),
 ('Allen, Mr. William Henry',),
 ('Moran, Mr. James',),
 ('McCarthy, Mr. Timothy J',),
 ('Palsson, Master. Gosta Leonard',),
 ('Saundercock, Mr. William Henry',),
 ('Andersson, Mr. Anders Johan',),
 ('Vestrom, Miss. Hulda Amanda Adolfina',),
 ('Rice, Master. Eugene',),
 ('Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',),
 ('Fynney, Mr. Joseph J',),
 ('Palsson, Miss. Torborg Danira',),
 ('Emir, Mr. Farred Chehab',),
 ('Fortune, Mr. Charles Alexander',),
 ('Todoroff, Mr. Lalio',),
 ('Uruchurtu, Don. Manuel E',),
 ('Wheadon, Mr. Edward H',),
 ('Meyer, Mr. Edgar Joseph',),
 ('Holverson, Mr. Alexander Oskar',),
 ('Cann, Mr. Ernest Charles',),
 ('Vander Planke, Miss. Augusta Maria',),
 ('Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',),
 ('Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',),
 ('Kraeff, Mr. Theodor',),
 ('Rogers, Mr. William John',),
 ('Lennon, Mr. Denis',),
 ('Samaan, Mr. Youssef',),
 ('Arnold-Franchi, Mrs. Josef (Josefine Franchi)',),
 ('Panula, Master. Juha Niilo',),
 ('Nosworthy, Mr. Richard Cater',),
 ('Ostby, Mr. Engelhart Cornelius',),
 ('Novel, Mr. Mansouer',),
 ('Goodwin, Master. William Frederick',),
 ('Sirayanian, Mr. Orsen',),
 ('Harris, Mr. Henry Birkhardt',),
 ('Skoog, Master. Harald',),
 ('Stewart, Mr. Albert A',),
 ('Crease, Mr. Ernest James',),
 ('Kink, Mr. Vincenz',),
 ('Jenkin, Mr. Stephen Curnow',),
 ('Goodwin, Miss. Lillian Amy',),
 ('Hood, Mr. Ambrose Jr',),
 ('Chronopoulos, Mr. Apostolos',),
 ('Moen, Mr. Sigurd Hansen',),
 ('Staneff, Mr. Ivan',),
 ('Moutal, Mr. Rahamin Haim',),
 ('Waelens, Mr. Achille',),
 ('Carrau, Mr. Francisco M',),
 ('Ford, Mr. William Neal',),
 ('Slocovski, Mr. Selman Francis',),
 ('Celotti, Mr. Francesco',),
 ('Christmann, Mr. Emil',),
 ('Andreasson, Mr. Paul Edvin',),
 ('Chaffee, Mr. Herbert Fuller',),
 ('Dean, Mr. Bertram Frank',),
 ('Coxon, Mr. Daniel',),
 ('Shorney, Mr. Charles Joseph',),
 ('Goldschmidt, Mr. George B',),
 ('Kantor, Mr. Sinai',),
 ('Petranec, Miss. Matilda',),
 ('Petroff, Mr. Pastcho ("Pentcho")',),
 ('White, Mr. Richard Frasar',),
 ('Johansson, Mr. Gustaf Joel',),
 ('Gustafsson, Mr. Anders Vilhelm',),
 ('Mionoff, Mr. Stoytcho',),
 ('Rekic, Mr. Tido',),
 ('Porter, Mr. Walter Chamberlain',),
 ('Zabour, Miss. Hileni',),
 ('Barton, Mr. David John',),
 ('Jussila, Miss. Katriina',),
 ('Attalah, Miss. Malake',),
 ('Pekoniemi, Mr. Edvard',),
 ('Connors, Mr. Patrick',),
 ('Turpin, Mr. William John Robert',),
 ('Baxter, Mr. Quigg Edmond',),
 ('Andersson, Miss. Ellis Anna Maria',),
 ('Hickman, Mr. Stanley George',),
 ('Moore, Mr. Leonard Charles',),
 ('Nasser, Mr. Nicholas',),
 ('White, Mr. Percival Wayland',),
 ('McMahon, Mr. Martin',),
 ('Ekstrom, Mr. Johan',),
 ('Drazenoic, Mr. Jozef',),
 ('Coelho, Mr. Domingos Fernandeo',),
 ('Robins, Mrs. Alexander A (Grace Charity Laury)',),
 ('Sobey, Mr. Samuel James Hayden',),
 ('Richard, Mr. Emile',),
 ('Futrelle, Mr. Jacques Heath',),
 ('Osen, Mr. Olaf Elon',),
 ('Giglio, Mr. Victor',),
 ('Boulos, Mrs. Joseph (Sultana)',),
 ('Burke, Mr. Jeremiah',),
 ('Andrew, Mr. Edgardo Samuel',),
 ('Nicholls, Mr. Joseph Charles',),
 ('Ford, Miss. Robina Maggie "Ruby"',),
 ('Navratil, Mr. Michel ("Louis M Hoffman")',),
 ('Byles, Rev. Thomas Roussel Davids',),
 ('Bateman, Rev. Robert James',),
 ('Meo, Mr. Alfonzo',),
 ('van Billiard, Mr. Austin Blyler',),
 ('Olsen, Mr. Ole Martin',),
 ('Williams, Mr. Charles Duane',),
 ('Corn, Mr. Harry',),
 ('Smiljanic, Mr. Mile',),
 ('Sage, Master. Thomas Henry',),
 ('Cribb, Mr. John Hatfield',),
 ('Bengtsson, Mr. John Viktor',),
 ('Calic, Mr. Jovo',),
 ('Panula, Master. Eino Viljami',),
 ('Skoog, Mrs. William (Anna Bernhardina Karlsson)',),
 ('Baumann, Mr. John D',),
 ('Ling, Mr. Lee',),
 ('Van der hoef, Mr. Wyckoff',),
 ('Rice, Master. Arthur',),
 ('Sivola, Mr. Antti Wilhelm',),
 ('Smith, Mr. James Clinch',),
 ('Klasen, Mr. Klas Albin',),
 ('Lefebre, Master. Henry Forbes',),
 ('Isham, Miss. Ann Elizabeth',),
 ('Hale, Mr. Reginald',),
 ('Leonard, Mr. Lionel',),
 ('Sage, Miss. Constance Gladys',),
 ('Pernot, Mr. Rene',),
 ('Asplund, Master. Clarence Gustaf Hugo',),
 ('Rood, Mr. Hugh Roscoe',),
 ('Bourke, Mr. John',),
 ('Turcin, Mr. Stjepan',),
 ('Carbines, Mr. William',),
 ('Mernagh, Mr. Robert',),
 ('Olsen, Mr. Karl Siegwart Andreas',),
 ('Yrois, Miss. Henriette ("Mrs Harbeck")',),
 ('Vande Walle, Mr. Nestor Cyriel',),
 ('Sage, Mr. Frederick',),
 ('Johanson, Mr. Jakob Alfred',),
 ('Youseff, Mr. Gerious',),
 ('Strom, Miss. Telma Matilda',),
 ('Backstrom, Mr. Karl Alfred',),
 ('Ali, Mr. Ahmed',),
 ('Perkin, Mr. John Henry',),
 ('Givard, Mr. Hans Kristensen',),
 ('Kiernan, Mr. Philip',),
 ('Jacobsohn, Mr. Sidney Samuel',),
 ('Harris, Mr. Walter',),
 ('Bracken, Mr. James H',),
 ('Green, Mr. George Henry',),
 ('Nenkoff, Mr. Christo',),
 ('Berglund, Mr. Karl Ivar Sven',),
 ('Lovell, Mr. John Hall ("Henry")',),
 ('Fahlstrom, Mr. Arne Jonas',),
 ('Lefebre, Miss. Mathilde',),
 ('Larsson, Mr. Bengt Edvin',),
 ('Sjostedt, Mr. Ernst Adolf',),
 ('Leyson, Mr. Robert William Norman',),
 ('Harknett, Miss. Alice Phoebe',),
 ('Hold, Mr. Stephen',),
 ('Pengelly, Mr. Frederick William',),
 ('Hunt, Mr. George Henry',),
 ('Zabour, Miss. Thamine',),
 ('Coleridge, Mr. Reginald Charles',),
 ('Maenpaa, Mr. Matti Alexanteri',),
 ('Attalah, Mr. Sleiman',),
 ('Minahan, Dr. William Edward',),
 ('Lindahl, Miss. Agda Thorilda Viktoria',),
 ('Carter, Rev. Ernest Courtenay',),
 ('Reed, Mr. James George',),
 ('Strom, Mrs. Wilhelm (Elna Matilda Persson)',),
 ('Stead, Mr. William Thomas',),
 ('Lobb, Mr. William Arthur',),
 ('Rosblom, Mrs. Viktor (Helena Wilhelmina)',),
 ('Smith, Mr. Thomas',),
 ('Taussig, Mr. Emil',),
 ('Harrison, Mr. William',),
 ('Henry, Miss. Delia',),
 ('Reeves, Mr. David',),
 ('Panula, Mr. Ernesti Arvid',),
 ('Cairns, Mr. Alexander',),
 ('Natsch, Mr. Charles H',),
 ('Lindblom, Miss. Augusta Charlotta',),
 ('Parkes, Mr. Francis "Frank"',),
 ('Rice, Master. Eric',),
 ('Duane, Mr. Frank',),
 ('Olsson, Mr. Nils Johan Goransson',),
 ('de Pelsmaeker, Mr. Alfons',),
 ('Smith, Mr. Richard William',),
 ('Stankovic, Mr. Ivan',),
 ('Naidenoff, Mr. Penko',),
 ('Levy, Mr. Rene Jacques',),
 ('Haas, Miss. Aloisia',),
 ('Mineff, Mr. Ivan',),
 ('Lewy, Mr. Ervin G',),
 ('Hanna, Mr. Mansour',),
 ('Allison, Miss. Helen Loraine',),
 ('Johnson, Mr. William Cahoone Jr',),
 ('Williams, Mr. Howard Hugh "Harry"',),
 ('Abelson, Mr. Samuel',),
 ('Lahtinen, Mrs. William (Anna Sylfven)',),
 ('Hendekovic, Mr. Ignjac',),
 ('Hart, Mr. Benjamin',),
 ('Moraweck, Dr. Ernest',),
 ('Dennis, Mr. Samuel',),
 ('Danoff, Mr. Yoto',),
 ('Sage, Mr. George John Jr',),
 ('Nysveen, Mr. Johan Hansen',),
 ('Partner, Mr. Austen',),
 ('Graham, Mr. George Edward',),
 ('Vander Planke, Mr. Leo Edmondus',),
 ('Denkoff, Mr. Mitto',),
 ('Pears, Mr. Thomas Clinton',),
 ('Blackwell, Mr. Stephen Weart',),
 ('Collander, Mr. Erik Gustaf',),
 ('Sedgwick, Mr. Charles Frederick Waddington',),
 ('Fox, Mr. Stanley Hubert',),
 ('Dimic, Mr. Jovan',),
 ('Odahl, Mr. Nils Martin',),
 ('Williams-Lambert, Mr. Fletcher Fellows',),
 ('Elias, Mr. Tannous',),
 ('Arnold-Franchi, Mr. Josef',),
 ('Yousif, Mr. Wazli',),
 ('Vanden Steen, Mr. Leo Peter',),
 ('Funk, Miss. Annie Clemmer',),
 ('Skoog, Mr. Wilhelm',),
 ('del Carlo, Mr. Sebastiano',),
 ('Barbara, Mrs. (Catherine David)',),
 ('Asim, Mr. Adola',),
 ("O'Brien, Mr. Thomas",),
 ('Adahl, Mr. Mauritz Nils Martin',),
 ('Wiklund, Mr. Jakob Alfred',),
 ('Beavan, Mr. William Thomas',),
 ('Ringhini, Mr. Sante',),
 ('Palsson, Miss. Stina Viola',),
 ('Widener, Mr. Harry Elkins',),
 ('Betros, Mr. Tannous',),
 ('Gustafsson, Mr. Karl Gideon',),
 ('Tikkanen, Mr. Juho',),
 ('Plotcharsky, Mr. Vasil',),
 ('Davies, Mr. Charles Henry',),
 ('Goodwin, Master. Sidney Leonard',),
 ('Sadlier, Mr. Matthew',),
 ('Gustafsson, Mr. Johan Birger',),
 ('Johansson, Mr. Erik',),
 ('Olsson, Miss. Elina',),
 ('McKane, Mr. Peter David',),
 ('Pain, Dr. Alfred',),
 ('Adams, Mr. John',),
 ('Jussila, Miss. Mari Aina',),
 ('Hakkarainen, Mr. Pekka Pietari',),
 ('Oreskovic, Miss. Marija',),
 ('Gale, Mr. Shadrach',),
 ('Widegren, Mr. Carl/Charles Peter',),
 ('Birkeland, Mr. Hans Martin Monsen',),
 ('Lefebre, Miss. Ida',),
 ('Sdycoff, Mr. Todor',),
 ('Hart, Mr. Henry',),
 ('Cunningham, Mr. Alfred Fleming',),
 ('Meek, Mrs. Thomas (Annie Louise Rowley)',),
 ('Matthews, Mr. William John',),
 ('Van Impe, Miss. Catharina',),
 ('Gheorgheff, Mr. Stanio',),
 ('Charters, Mr. David',),
 ('Zimmerman, Mr. Leo',),
 ('Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',),
 ('Rosblom, Mr. Viktor Richard',),
 ('Wiseman, Mr. Phillippe',),
 ('Flynn, Mr. James',),
 ('Kallio, Mr. Nikolai Erland',),
 ('Silvey, Mr. William Baird',),
 ('Ford, Miss. Doolina Margaret "Daisy"',),
 ('Fortune, Mr. Mark',),
 ('Kvillner, Mr. Johan Henrik Johannesson',),
 ('Hampe, Mr. Leon',),
 ('Petterson, Mr. Johan Emil',),
 ('West, Mr. Edwy Arthur',),
 ('Hagland, Mr. Ingvald Olai Olsen',),
 ('Foreman, Mr. Benjamin Laventall',),
 ('Peduzzi, Mr. Joseph',),
 ('Millet, Mr. Francis Davis',),
 ("O'Connor, Mr. Maurice",),
 ('Morley, Mr. William',),
 ('Gee, Mr. Arthur H',),
 ('Milling, Mr. Jacob Christian',),
 ('Maisner, Mr. Simon',),
 ('Goncalves, Mr. Manuel Estanslas',),
 ('Campbell, Mr. William',),
 ('Smart, Mr. John Montgomery',),
 ('Scanlan, Mr. James',),
 ('Keefe, Mr. Arthur',),
 ('Cacic, Mr. Luka',),
 ('Strandberg, Miss. Ida Sofia',),
 ('Clifford, Mr. George Quincy',),
 ('Renouf, Mr. Peter Henry',),
 ('Braund, Mr. Lewis Richard',),
 ('Karlsson, Mr. Nils August',),
 ('Goodwin, Master. Harold Victor',),
 ('Frost, Mr. Anthony Wood "Archie"',),
 ('Rouse, Mr. Richard Henry',),
 ('Lefebre, Miss. Jeannie',),
 ('Kent, Mr. Edward Austin',),
 ('Somerton, Mr. Francis William',),
 ('Hagland, Mr. Konrad Mathias Reiersen',),
 ('Windelov, Mr. Einar',),
 ('Molson, Mr. Harry Markland',),
 ('Artagaveytia, Mr. Ramon',),
 ('Stanley, Mr. Edward Roland',),
 ('Yousseff, Mr. Gerious',),
 ('Shellard, Mr. Frederick William',),
 ('Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',),
 ('Svensson, Mr. Olof',),
 ('Calic, Mr. Petar',),
 ('Canavan, Miss. Mary',),
 ("O'Sullivan, Miss. Bridget Mary",),
 ('Laitinen, Miss. Kristina Sofia',),
 ('Penasco y Castellana, Mr. Victor de Satode',),
 ('Olsen, Mr. Henry Margido',),
 ('Webber, Mr. James',),
 ('Coleff, Mr. Satio',),
 ('Walker, Mr. William Anderson',),
 ('Ryan, Mr. Patrick',),
 ('Pavlovic, Mr. Stefo',),
 ('Vovk, Mr. Janko',),
 ('Lahoud, Mr. Sarkis',),
 ('Kassem, Mr. Fared',),
 ('Farrell, Mr. James',),
 ('Farthing, Mr. John',),
 ('Salonen, Mr. Johan Werner',),
 ('Hocking, Mr. Richard George',),
 ('Toufik, Mr. Nakli',),
 ('Elias, Mr. Joseph Jr',),
 ('Cacic, Miss. Marija',),
 ('Butt, Major. Archibald Willingham',),
 ('Risien, Mr. Samuel Beard',),
 ('Andersson, Miss. Ingeborg Constanzia',),
 ('Andersson, Miss. Sigrid Elisabeth',),
 ('Douglas, Mr. Walter Donald',),
 ('Nicholson, Mr. Arthur Ernest',),
 ('Goldsmith, Mr. Frank John',),
 ('Sharp, Mr. Percival James R',),
 ("O'Brien, Mr. Timothy",),
 ('Wright, Mr. George',),
 ('Robbins, Mr. Victor',),
 ('Morrow, Mr. Thomas Rowan',),
 ('Sivic, Mr. Husein',),
 ('Norman, Mr. Robert Douglas',),
 ('Simmons, Mr. John',),
 ('Meanwell, Miss. (Marion Ogden)',),
 ('Davies, Mr. Alfred J',),
 ('Stoytcheff, Mr. Ilia',),
 ('Palsson, Mrs. Nils (Alma Cornelia Berglund)',),
 ('Doharr, Mr. Tannous',),
 ('Rush, Mr. Alfred George John',),
 ('Patchett, Mr. George',),
 ('Caram, Mrs. Joseph (Maria Elias)',),
 ('Downton, Mr. William James',),
 ('Ross, Mr. John Hugo',),
 ('Paulner, Mr. Uscher',),
 ('Jarvis, Mr. John Denzil',),
 ('Gilinski, Mr. Eliezer',),
 ('Murdlin, Mr. Joseph',),
 ('Rintamaki, Mr. Matti',),
 ('Elsbury, Mr. William James',),
 ('Bourke, Miss. Mary',),
 ('Chapman, Mr. John Henry',),
 ('Van Impe, Mr. Jean Baptiste',),
 ('Johnson, Mr. Alfred',),
 ('Boulos, Mr. Hanna',),
 ('Slabenoff, Mr. Petco',),
 ('Harrington, Mr. Charles H',),
 ('Torber, Mr. Ernst William',),
 ('Lindell, Mr. Edvard Bengtsson',),
 ('Karaic, Mr. Milan',),
 ('Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',),
 ('Jardin, Mr. Jose Neto',),
 ('Horgan, Mr. John',),
 ('Brocklebank, Mr. William Alfred',),
 ('Danbom, Mr. Ernst Gilbert',),
 ('Lobb, Mrs. William Arthur (Cordelia K Stanlick)',),
 ('Gavey, Mr. Lawrence',),
 ('Yasbeck, Mr. Antoni',),
 ('Hansen, Mr. Henry Damsgaard',),
 ('Bowen, Mr. David John "Dai"',),
 ('Sutton, Mr. Frederick',),
 ('Kirkland, Rev. Charles Leonard',),
 ('Bostandyeff, Mr. Guentcho',),
 ("O'Connell, Mr. Patrick D",),
 ('Lundahl, Mr. Johan Svensson',),
 ('Parr, Mr. William Henry Marsh',),
 ('Skoog, Miss. Mabel',),
 ('Leinonen, Mr. Antti Gustaf',),
 ('Collyer, Mr. Harvey',),
 ('Panula, Mrs. Juha (Maria Emilia Ojala)',),
 ('Thorneycroft, Mr. Percival',),
 ('Jensen, Mr. Hans Peder',),
 ('Skoog, Miss. Margit Elizabeth',),
 ('Cor, Mr. Liudevit',),
 ('Willey, Mr. Edward',),
 ('Mitkoff, Mr. Mito',),
 ('Kalvik, Mr. Johannes Halvorsen',),
 ('Hegarty, Miss. Hanora "Nora"',),
 ('Hickman, Mr. Leonard Mark',),
 ('Radeff, Mr. Alexander',),
 ('Bourke, Mrs. John (Catherine)',),
 ('Eitemiller, Mr. George Floyd',),
 ('Newell, Mr. Arthur Webster',),
 ('Badt, Mr. Mohamed',),
 ('Colley, Mr. Edward Pomeroy',),
 ('Coleff, Mr. Peju',),
 ('Hickman, Mr. Lewis',),
 ('Butler, Mr. Reginald Fenton',),
 ('Rommetvedt, Mr. Knud Paust',),
 ('Cook, Mr. Jacob',),
 ('Davidson, Mr. Thornton',),
 ('Mitchell, Mr. Henry Michael',),
 ('Watson, Mr. Ennis Hastings',),
 ('Edvardsson, Mr. Gustaf Hjalmar',),
 ('Sawyer, Mr. Frederick Charles',),
 ('Goodwin, Mrs. Frederick (Augusta Tyler)',),
 ('Peters, Miss. Katie',),
 ('Olsvigen, Mr. Thor Anderson',),
 ('Goodwin, Mr. Charles Edward',),
 ('Brown, Mr. Thomas William Solomon',),
 ('Laroche, Mr. Joseph Philippe Lemercier',),
 ('Panula, Mr. Jaako Arnold',),
 ('Dakic, Mr. Branko',),
 ('Fischer, Mr. Eberhard Thelander',),
 ('Saad, Mr. Khalil',),
 ('Weir, Col. John',),
 ('Chapman, Mr. Charles Henry',),
 ('Kelly, Mr. James',),
 ('Thayer, Mr. John Borland',),
 ('Humblen, Mr. Adolf Mathias Nicolai Olsen',),
 ('Barbara, Miss. Saiide',),
 ('Gallagher, Mr. Martin',),
 ('Hansen, Mr. Henrik Juul',),
 ('Morley, Mr. Henry Samuel ("Mr Henry Marshall")',),
 ('Klaber, Mr. Herman',),
 ('Larsson, Mr. August Viktor',),
 ('Greenberg, Mr. Samuel',),
 ('Soholt, Mr. Peter Andreas Lauritz Andersen',),
 ('McEvoy, Mr. Michael',),
 ('Johnson, Mr. Malkolm Joackim',),
 ('Jensen, Mr. Svend Lauritz',),
 ('Gillespie, Mr. William Henry',),
 ('Hodges, Mr. Henry Price',),
 ('Oreskovic, Mr. Luka',),
 ('Bryhl, Mr. Kurt Arnold Gottfrid',),
 ('Ilmakangas, Miss. Pieta Sofia',),
 ('Hassan, Mr. Houssein G N',),
 ('Knight, Mr. Robert J',),
 ('Berriman, Mr. William John',),
 ('Troupiansky, Mr. Moses Aaron',),
 ('Williams, Mr. Leslie',),
 ('Ford, Mrs. Edward (Margaret Ann Watson)',),
 ('Ivanoff, Mr. Kanio',),
 ('Nankoff, Mr. Minko',),
 ('Cavendish, Mr. Tyrell William',),
 ('McNamee, Mr. Neal',),
 ('Crosby, Capt. Edward Gifford',),
 ('Abbott, Mr. Rossmore Edward',),
 ('Marvin, Mr. Daniel Warner',),
 ('Connaghton, Mr. Michael',),
 ('Vande Velde, Mr. Johannes Joseph',),
 ('Jonkoff, Mr. Lalio',),
 ('Carlsson, Mr. August Sigfrid',),
 ('Bailey, Mr. Percy Andrew',),
 ('Theobald, Mr. Thomas Leonard',),
 ('Garfirth, Mr. John',),
 ('Nirva, Mr. Iisakki Antino Aijo',),
 ('Eklund, Mr. Hans Linus',),
 ('Brewe, Dr. Arthur Jackson',),
 ('Mangan, Miss. Mary',),
 ('Moran, Mr. Daniel J',),
 ('Gronnestad, Mr. Daniel Danielsen',),
 ('Lievens, Mr. Rene Aime',),
 ('Jensen, Mr. Niels Peder',),
 ('Mack, Mrs. (Mary)',),
 ('Elias, Mr. Dibo',),
 ('Myhrman, Mr. Pehr Fabian Oliver Malkolm',),
 ('Tobin, Mr. Roger',),
 ('Kilgannon, Mr. Thomas J',),
 ('Long, Mr. Milton Clyde',),
 ('Johnston, Mr. Andrew G',),
 ('Ali, Mr. William',),
 ('Harmer, Mr. Abraham (David Lishin)',),
 ('Rice, Master. George Hugh',),
 ('Guggenheim, Mr. Benjamin',),
 ('Keane, Mr. Andrew "Andy"',),
 ('Gaskell, Mr. Alfred',),
 ('Sage, Miss. Stella Anna',),
 ('Hoyt, Mr. William Fisher',),
 ('Dantcheff, Mr. Ristiu',),
 ('Otter, Mr. Richard',),
 ('Ibrahim Shawah, Mr. Yousseff',),
 ('Van Impe, Mrs. Jean Baptiste (Rosalie Paula Govaert)',),
 ('Ponesell, Mr. Martin',),
 ('Johansson, Mr. Karl Johan',),
 ('Andrews, Mr. Thomas Jr',),
 ('Pettersson, Miss. Ellen Natalia',),
 ('Meyer, Mr. August',),
 ('Alexander, Mr. William',),
 ('Lester, Mr. James',),
 ('Slemen, Mr. Richard James',),
 ('Andersson, Miss. Ebba Iris Alfrida',),
 ('Tomlin, Mr. Ernest Portage',),
 ('Fry, Mr. Richard',),
 ('Heininen, Miss. Wendla Maria',),
 ('Mallet, Mr. Albert',),
 ('Holm, Mr. John Fredrik Alexander',),
 ('Skoog, Master. Karl Thorsten',),
 ('Reuchlin, Jonkheer. John George',),
 ('Panula, Master. Urho Abraham',),
 ('Flynn, Mr. John',),
 ('Lam, Mr. Len',),
 ('Saad, Mr. Amin',),
 ('Augustsson, Mr. Albert',),
 ('Allum, Mr. Owen George',),
 ('Pasic, Mr. Jakob',),
 ('Sirota, Mr. Maurice',),
 ('Alhomaki, Mr. Ilmari Rudolf',),
 ('Mudd, Mr. Thomas Charles',),
 ('Lemberopolous, Mr. Peter L',),
 ('Culumovic, Mr. Jeso',),
 ('Abbing, Mr. Anthony',),
 ('Sage, Mr. Douglas Bullen',),
 ('Markoff, Mr. Marin',),
 ('Harper, Rev. John',),
 ('Andersson, Master. Sigvard Harald Elias',),
 ('Svensson, Mr. Johan',),
 ('Boulos, Miss. Nourelain',),
 ('Carter, Mrs. Ernest Courtenay (Lilian Hughes)',),
 ('Razi, Mr. Raihed',),
 ('Hansen, Mr. Claus Peter',),
 ('Giles, Mr. Frederick Edward',),
 ('Sage, Miss. Dorothy Edith "Dolly"',),
 ('Gill, Mr. John William',),
 ('Roebling, Mr. Washington Augustus II',),
 ('van Melkebeke, Mr. Philemon',),
 ('Balkic, Mr. Cerin',),
 ('Carlsson, Mr. Frans Olof',),
 ('Vander Cruyssen, Mr. Victor',),
 ('Gustafsson, Mr. Alfred Ossian',),
 ('Petroff, Mr. Nedelio',),
 ('Laleff, Mr. Kristo',),
 ('Markun, Mr. Johann',),
 ('Dahlberg, Miss. Gerda Ulrika',),
 ('Banfield, Mr. Frederick James',),
 ('Sutehall, Mr. Henry Jr',),
 ('Rice, Mrs. William (Margaret Norton)',),
 ('Montvila, Rev. Juozas',),
 ('Johnston, Miss. Catherine Helen "Carrie"',),
 ('Dooley, Mr. Patrick',)]

In [145]:
%%sql
SELECT*FROM Embarquement where Cabin is null;

 * postgresql://oceane:***@localhost/postgres
687 rows affected.

[('A/5 21171', 7.25, None, 'S', 0, 'Braund, Mr. Owen Harris', 1, 3, 1),
 ('STON/O2. 3101282', 7.925, None, 'S', 1, 'Heikkinen, Miss. Laina', 0, 3, 3),
 ('373450', 8.05, None, 'S', 0, 'Allen, Mr. William Henry', 0, 3, 5),
 ('330877', 8.4583, None, 'Q', 0, 'Moran, Mr. James', 0, 3, 6),
 ('349909', 21.075, None, 'S', 0, 'Palsson, Master. Gosta Leonard', 3, 3, 8),
 ('347742', 11.1333, None, 'S', 1, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 0, 3, 9),
 ('237736', 30.0708, None, 'C', 1, 'Nasser, Mrs. Nicholas (Adele Achem)', 1, 2, 10),
 ('A/5. 2151', 8.05, None, 'S', 0, 'Saundercock, Mr. William Henry', 0, 3, 13),
 ('347082', 31.275, None, 'S', 0, 'Andersson, Mr. Anders Johan', 1, 3, 14),
 ('350406', 7.8542, None, 'S', 0, 'Vestrom, Miss. Hulda Amanda Adolfina', 0, 3, 15),
 ('248706', 16.0, None, 'S', 1, 'Hewlett, Mrs. (Mary D Kingcome) ', 0, 2, 16),
 ('382652', 29.125, None, 'Q', 0, 'Rice, Master. Eugene', 4, 3, 17),
 ('244373', 13.0, None, 'S', 1, 'Williams, Mr. Charles Eugene', 0, 2, 18),
 ('345763', 18.0, None, 'S', 0, 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 1, 3, 19),
 ('2649', 7.225, None, 'C', 1, 'Masselmani, Mrs. Fatima', 0, 3, 20),
 ('239865', 26.0, None, 'S', 0, 'Fynney, Mr. Joseph J', 0, 2, 21),
 ('330923', 8.0292, None, 'Q', 1, 'McGowan, Miss. Anna "Annie"', 0, 3, 23),
 ('349909', 21.075, None, 'S', 0, 'Palsson, Miss. Torborg Danira', 3, 3, 25),
 ('347077', 31.3875, None, 'S', 1, 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 1, 3, 26),
 ('2631', 7.225, None, 'C', 0, 'Emir, Mr. Farred Chehab', 0, 3, 27),
 ('330959', 7.8792, None, 'Q', 1, 'O\'Dwyer, Miss. Ellen "Nellie"', 0, 3, 29),
 ('349216', 7.8958, None, 'S', 0, 'Todoroff, Mr. Lalio', 0, 3, 30),
 ('PC 17601', 27.7208, None, 'C', 0, 'Uruchurtu, Don. Manuel E', 0, 1, 31),
 ('335677', 7.75, None, 'Q', 1, 'Glynn, Miss. Mary Agatha', 0, 3, 33),
 ('C.A. 24579', 10.5, None, 'S', 0, 'Wheadon, Mr. Edward H', 0, 2, 34),
 ('PC 17604', 82.1708, None, 'C', 0, 'Meyer, Mr. Edgar Joseph', 1, 1, 35),
 ('113789', 52.0, None, 'S', 0, 'Holverson, Mr. Alexander Oskar', 1, 1, 36),
 ('2677', 7.2292, None, 'C', 1, 'Mamee, Mr. Hanna', 0, 3, 37),
 ('A./5. 2152', 8.05, None, 'S', 0, 'Cann, Mr. Ernest Charles', 0, 3, 38),
 ('345764', 18.0, None, 'S', 0, 'Vander Planke, Miss. Augusta Maria', 2, 3, 39),
 ('2651', 11.2417, None, 'C', 1, 'Nicola-Yarred, Miss. Jamila', 1, 3, 40),
 ('7546', 9.475, None, 'S', 0, 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 1, 3, 41),
 ('11668', 21.0, None, 'S', 0, 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 1, 2, 42),
 ('349253', 7.8958, None, 'C', 0, 'Kraeff, Mr. Theodor', 0, 3, 43),
 ('SC/Paris 2123', 41.5792, None, 'C', 1, 'Laroche, Miss. Simonne Marie Anne Andree', 1, 2, 44),
 ('330958', 7.8792, None, 'Q', 1, 'Devaney, Miss. Margaret Delia', 0, 3, 45),
 ('S.C./A.4. 23567', 8.05, None, 'S', 0, 'Rogers, Mr. William John', 0, 3, 46),
 ('370371', 15.5, None, 'Q', 0, 'Lennon, Mr. Denis', 1, 3, 47),
 ('14311', 7.75, None, 'Q', 1, "O'Driscoll, Miss. Bridget", 0, 3, 48),
 ('2662', 21.6792, None, 'C', 0, 'Samaan, Mr. Youssef', 2, 3, 49),
 ('349237', 17.8, None, 'S', 0, 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 1, 3, 50),
 ('3101295', 39.6875, None, 'S', 0, 'Panula, Master. Juha Niilo', 4, 3, 51),
 ('A/4. 39886', 7.8, None, 'S', 0, 'Nosworthy, Mr. Richard Cater', 0, 3, 52),
 ('2926', 26.0, None, 'S', 1, 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 1, 2, 54),
 ('C.A. 31026', 10.5, None, 'S', 1, 'Rugg, Miss. Emily', 0, 2, 57),
 ('2697', 7.2292, None, 'C', 0, 'Novel, Mr. Mansouer', 0, 3, 58),
 ('C.A. 34651', 27.75, None, 'S', 1, 'West, Miss. Constance Mirium', 1, 2, 59),
 ('CA 2144', 46.9, None, 'S', 0, 'Goodwin, Master. William Frederick', 5, 3, 60),
 ('2669', 7.2292, None, 'C', 0, 'Sirayanian, Mr. Orsen', 0, 3, 61),
 ('347088', 27.9, None, 'S', 0, 'Skoog, Master. Harald', 3, 3, 64),
 ('PC 17605', 27.7208, None, 'C', 0, 'Stewart, Mr. Albert A', 0, 1, 65),
 ('2661', 15.2458, None, 'C', 1, 'Moubarek, Master. Gerios', 1, 3, 66),
 ('S.P. 3464', 8.1583, None, 'S', 0, 'Crease, Mr. Ernest James', 0, 3, 68),
 ('3101281', 7.925, None, 'S', 1, 'Andersson, Miss. Erna Alexandra', 4, 3, 69),
 ('315151', 8.6625, None, 'S', 0, 'Kink, Mr. Vincenz', 2, 3, 70),
 ('C.A. 33111', 10.5, None, 'S', 0, 'Jenkin, Mr. Stephen Curnow', 0, 2, 71),
 ('CA 2144', 46.9, None, 'S', 0, 'Goodwin, Miss. Lillian Amy', 5, 3, 72),
 ('S.O.C. 14879', 73.5, None, 'S', 0, 'Hood, Mr. Ambrose Jr', 0, 2, 73),
 ('2680', 14.4542, None, 'C', 0, 'Chronopoulos, Mr. Apostolos', 1, 3, 74),
 ('1601', 56.4958, None, 'S', 1, 'Bing, Mr. Lee', 0, 3, 75),
 ('349208', 7.8958, None, 'S', 0, 'Staneff, Mr. Ivan', 0, 3, 77),
 ('374746', 8.05, None, 'S', 0, 'Moutal, Mr. Rahamin Haim', 0, 3, 78),
 ('248738', 29.0, None, 'S', 1, 'Caldwell, Master. Alden Gates', 0, 2, 79),
 ('364516', 12.475, None, 'S', 1, 'Dowdell, Miss. Elizabeth', 0, 3, 80),
 ('345767', 9.0, None, 'S', 0, 'Waelens, Mr. Achille', 0, 3, 81),
 ('345779', 9.5, None, 'S', 1, 'Sheerlinck, Mr. Jan Baptist', 0, 3, 82),
 ('330932', 7.7875, None, 'Q', 1, 'McDermott, Miss. Brigdet Delia', 0, 3, 83),
 ('113059', 47.1, None, 'S', 0, 'Carrau, Mr. Francisco M', 0, 1, 84),
 ('SO/C 14885', 10.5, None, 'S', 1, 'Ilett, Miss. Bertha', 0, 2, 85),
 ('3101278', 15.85, None, 'S', 1, 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 3, 3, 86),
 ('W./C. 6608', 34.375, None, 'S', 0, 'Ford, Mr. William Neal', 1, 3, 87),
 ('SOTON/OQ 392086', 8.05, None, 'S', 0, 'Slocovski, Mr. Selman Francis', 0, 3, 88),
 ('343275', 8.05, None, 'S', 0, 'Celotti, Mr. Francesco', 0, 3, 90),
 ('343276', 8.05, None, 'S', 0, 'Christmann, Mr. Emil', 0, 3, 91),
 ('347466', 7.8542, None, 'S', 0, 'Andreasson, Mr. Paul Edvin', 0, 3, 92),
 ('C.A. 2315', 20.575, None, 'S', 0, 'Dean, Mr. Bertram Frank', 1, 3, 94),
 ('364500', 7.25, None, 'S', 0, 'Coxon, Mr. Daniel', 0, 3, 95),
 ('374910', 8.05, None, 'S', 0, 'Shorney, Mr. Charles Joseph', 0, 3, 96),
 ('231919', 23.0, None, 'S', 1, 'Doling, Mrs. John T (Ada Julia Bone)', 0, 2, 99),
 ('244367', 26.0, None, 'S', 0, 'Kantor, Mr. Sinai', 1, 2, 100),
 ('349245', 7.8958, None, 'S', 0, 'Petranec, Miss. Matilda', 0, 3, 101),
 ('349215', 7.8958, None, 'S', 0, 'Petroff, Mr. Pastcho ("Pentcho")', 0, 3, 102),
 ('7540', 8.6542, None, 'S', 0, 'Johansson, Mr. Gustaf Joel', 0, 3, 104),
 ('3101276', 7.925, None, 'S', 0, 'Gustafsson, Mr. Anders Vilhelm', 2, 3, 105),
 ('349207', 7.8958, None, 'S', 0, 'Mionoff, Mr. Stoytcho', 0, 3, 106),
 ('343120', 7.65, None, 'S', 1, 'Salkjelsvik, Miss. Anna Kristine', 0, 3, 107),
 ('312991', 7.775, None, 'S', 1, 'Moss, Mr. Albert Johan', 0, 3, 108),
 ('349249', 7.8958, None, 'S', 0, 'Rekic, Mr. Tido', 0, 3, 109),
 ('371110', 24.15, None, 'Q', 1, 'Moran, Miss. Bertha', 1, 3, 110),
 ('2665', 14.4542, None, 'C', 0, 'Zabour, Miss. Hileni', 1, 3, 112),
 ('324669', 8.05, None, 'S', 0, 'Barton, Mr. David John', 0, 3, 113),
 ('4136', 9.825, None, 'S', 0, 'Jussila, Miss. Katriina', 1, 3, 114),
 ('2627', 14.4583, None, 'C', 0, 'Attalah, Miss. Malake', 0, 3, 115),
 ('STON/O 2. 3101294', 7.925, None, 'S', 0, 'Pekoniemi, Mr. Edvard', 0, 3, 116),
 ('370369', 7.75, None, 'Q', 0, 'Connors, Mr. Patrick', 0, 3, 117),
 ('11668', 21.0, None, 'S', 0, 'Turpin, Mr. William John Robert', 1, 2, 118),
 ('347082', 31.275, None, 'S', 0, 'Andersson, Miss. Ellis Anna Maria', 4, 3, 120),
 ('S.O.C. 14879', 73.5, None, 'S', 0, 'Hickman, Mr. Stanley George', 2, 2, 121),
 ('A4. 54510', 8.05, None, 'S', 0, 'Moore, Mr. Leonard Charles', 0, 3, 122),
 ('237736', 30.0708, None, 'C', 0, 'Nasser, Mr. Nicholas', 1, 2, 123),
 ('2651', 11.2417, None, 'C', 1, 'Nicola-Yarred, Master. Elias', 1, 3, 126),
 ('370372', 7.75, None, 'Q', 0, 'McMahon, Mr. Martin', 0, 3, 127),
 ('C 17369', 7.1417, None, 'S', 1, 'Madsen, Mr. Fridtjof Arne', 0, 3, 128),
 ('347061', 6.975, None, 'S', 0, 'Ekstrom, Mr. Johan', 0, 3, 130),
 ('349241', 7.8958, None, 'C', 0, 'Drazenoic, Mr. Jozef', 0, 3, 131),
 ('SOTON/O.Q. 3101307', 7.05, None, 'S', 0, 'Coelho, Mr. Domingos Fernandeo', 0, 3, 132),
 ('A/5. 3337', 14.5, None, 'S', 0, 'Robins, Mrs. Alexander A (Grace Charity Laury)', 1, 3, 133),
 ('228414', 26.0, None, 'S', 1, 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)', 1, 2, 134),
 ('C.A. 29178', 13.0, None, 'S', 0, 'Sobey, Mr. Samuel James Hayden', 0, 2, 135),
 ('SC/PARIS 2133', 15.0458, None, 'C', 0, 'Richard, Mr. Emile', 0, 2, 136),
 ('7534', 9.2167, None, 'S', 0, 'Osen, Mr. Olaf Elon', 0, 3, 139),
 ('2678', 15.2458, None, 'C', 0, 'Boulos, Mrs. Joseph (Sultana)', 0, 3, 141),
 ('347081', 7.75, None, 'S', 1, 'Nysten, Miss. Anna Sofia', 0, 3, 142),
 ('STON/O2. 3101279', 15.85, None, 'S', 1, 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)', 1, 3, 143),
 ('365222', 6.75, None, 'Q', 0, 'Burke, Mr. Jeremiah', 0, 3, 144),
 ('231945', 11.5, None, 'S', 0, 'Andrew, Mr. Edgardo Samuel', 0, 2, 145),
 ('C.A. 33112', 36.75, None, 'S', 0, 'Nicholls, Mr. Joseph Charles', 1, 2, 146),
 ('350043', 7.7958, None, 'S', 1, 'Andersson, Mr. August Edvard ("Wennerstrom")', 0, 3, 147),
 ('W./C. 6608', 34.375, None, 'S', 0, 'Ford, Miss. Robina Maggie "Ruby"', 2, 3, 148),
 ('244310', 13.0, None, 'S', 0, 'Byles, Rev. Thomas Roussel Davids', 0, 2, 150),
 ('S.O.P. 1166', 12.525, None, 'S', 0, 'Bateman, Rev. Robert James', 0, 2, 151),
 ('A.5. 11206', 8.05, None, 'S', 0, 'Meo, Mr. Alfonzo', 0, 3, 153),
 ('A/5. 851', 14.5, None, 'S', 0, 'van Billiard, Mr. Austin Blyler', 0, 3, 154),
 ('Fa 265302', 7.3125, None, 'S', 0, 'Olsen, Mr. Ole Martin', 0, 3, 155),
 ('PC 17597', 61.3792, None, 'C', 0, 'Williams, Mr. Charles Duane', 0, 1, 156),
 ('35851', 7.7333, None, 'Q', 1, 'Gilnagh, Miss. Katherine "Katie"', 0, 3, 157),
 ('SOTON/OQ 392090', 8.05, None, 'S', 0, 'Corn, Mr. Harry', 0, 3, 158),
 ('315037', 8.6625, None, 'S', 0, 'Smiljanic, Mr. Mile', 0, 3, 159),
 ('CA. 2343', 69.55, None, 'S', 0, 'Sage, Master. Thomas Henry', 8, 3, 160),
 ('371362', 16.1, None, 'S', 0, 'Cribb, Mr. John Hatfield', 0, 3, 161),
 ('C.A. 33595', 15.75, None, 'S', 1, 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)', 0, 2, 162),
 ('347068', 7.775, None, 'S', 0, 'Bengtsson, Mr. John Viktor', 0, 3, 163),
 ('315093', 8.6625, None, 'S', 0, 'Calic, Mr. Jovo', 0, 3, 164),
 ('3101295', 39.6875, None, 'S', 0, 'Panula, Master. Eino Viljami', 4, 3, 165),
 ('363291', 20.525, None, 'S', 1, 'Goldsmith, Master. Frank John William "Frankie"', 0, 3, 166),
 ('347088', 27.9, None, 'S', 0, 'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 1, 3, 168),
 ('PC 17318', 25.925, None, 'S', 0, 'Baumann, Mr. John D', 0, 1, 169),
 ('1601', 56.4958, None, 'S', 0, 'Ling, Mr. Lee', 0, 3, 170),
 ('382652', 29.125, None, 'Q', 0, 'Rice, Master. Arthur', 4, 3, 172),
 ('347742', 11.1333, None, 'S', 1, 'Johnson, Miss. Eleanor Ileen', 1, 3, 173),
 ('STON/O 2. 3101280', 7.925, None, 'S', 0, 'Sivola, Mr. Antti Wilhelm', 0, 3, 174),
 ('350404', 7.8542, None, 'S', 0, 'Klasen, Mr. Klas Albin', 1, 3, 176),
 ('4133', 25.4667, None, 'S', 0, 'Lefebre, Master. Henry Forbes', 3, 3, 177),
 ('250653', 13.0, None, 'S', 0, 'Hale, Mr. Reginald', 0, 2, 179),
 ('LINE', 0.0, None, 'S', 0, 'Leonard, Mr. Lionel', 0, 3, 180),
 ('CA. 2343', 69.55, None, 'S', 0, 'Sage, Miss. Constance Gladys', 8, 3, 181),
 ('SC/PARIS 2131', 15.05, None, 'C', 0, 'Pernot, Mr. Rene', 0, 2, 182),
 ('347077', 31.3875, None, 'S', 0, 'Asplund, Master. Clarence Gustaf Hugo', 4, 3, 183),
 ('315153', 22.025, None, 'S', 1, 'Kink-Heilmann, Miss. Luise Gretchen', 0, 3, 185),
 ('370365', 15.5, None, 'Q', 1, 'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)', 1, 3, 187),
 ('111428', 26.55, None, 'S', 1, 'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 0, 1, 188),
 ('364849', 15.5, None, 'Q', 0, 'Bourke, Mr. John', 1, 3, 189),
 ('349247', 7.8958, None, 'S', 0, 'Turcin, Mr. Stjepan', 0, 3, 190),
 ('234604', 13.0, None, 'S', 1, 'Pinsky, Mrs. (Rosa)', 0, 2, 191),
 ('28424', 13.0, None, 'S', 0, 'Carbines, Mr. William', 0, 2, 192),
 ('350046', 7.8542, None, 'S', 1, 'Andersen-Jensen, Miss. Carla Christine Nielsine', 1, 3, 193),
 ('368703', 7.75, None, 'Q', 0, 'Mernagh, Mr. Robert', 0, 3, 197),
 ('4579', 8.4042, None, 'S', 0, 'Olsen, Mr. Karl Siegwart Andreas', 0, 3, 198),
 ('370370', 7.75, None, 'Q', 1, 'Madigan, Miss. Margaret "Maggie"', 0, 3, 199),
 ('248747', 13.0, None, 'S', 0, 'Yrois, Miss. Henriette ("Mrs Harbeck")', 0, 2, 200),
 ('345770', 9.5, None, 'S', 0, 'Vande Walle, Mr. Nestor Cyriel', 0, 3, 201),
 ('CA. 2343', 69.55, None, 'S', 0, 'Sage, Mr. Frederick', 8, 3, 202),
 ('3101264', 6.4958, None, 'S', 0, 'Johanson, Mr. Jakob Alfred', 0, 3, 203),
 ('2628', 7.225, None, 'C', 0, 'Youseff, Mr. Gerious', 0, 3, 204),
 ('A/5 3540', 8.05, None, 'S', 1, 'Cohen, Mr. Gurshon "Gus"', 0, 3, 205),
 ('3101278', 15.85, None, 'S', 0, 'Backstrom, Mr. Karl Alfred', 1, 3, 207),
 ('2699', 18.7875, None, 'C', 1, 'Albimona, Mr. Nassef Cassem', 0, 3, 208),
 ('367231', 7.75, None, 'Q', 1, 'Carr, Miss. Helen "Ellen"', 0, 3, 209),
 ('SOTON/O.Q. 3101311', 7.05, None, 'S', 0, 'Ali, Mr. Ahmed', 0, 3, 211),
 ('F.C.C. 13528', 21.0, None, 'S', 1, 'Cameron, Miss. Clear Annie', 0, 2, 212),
 ('A/5 21174', 7.25, None, 'S', 0, 'Perkin, Mr. John Henry', 0, 3, 213),
 ('250646', 13.0, None, 'S', 0, 'Givard, Mr. Hans Kristensen', 0, 2, 214),
 ('367229', 7.75, None, 'Q', 0, 'Kiernan, Mr. Philip', 1, 3, 215),
 ('STON/O2. 3101283', 7.925, None, 'S', 1, 'Honkanen, Miss. Eliina', 0, 3, 217),
 ('243847', 27.0, None, 'S', 0, 'Jacobsohn, Mr. Sidney Samuel', 1, 2, 218),
 ('W/C 14208', 10.5, None, 'S', 0, 'Harris, Mr. Walter', 0, 2, 220),
 ('SOTON/OQ 392089', 8.05, None, 'S', 1, 'Sunderland, Mr. Victor Francis', 0, 3, 221),
 ('220367', 13.0, None, 'S', 0, 'Bracken, Mr. James H', 0, 2, 222),
 ('21440', 8.05, None, 'S', 0, 'Green, Mr. George Henry', 0, 3, 223),
 ('349234', 7.8958, None, 'S', 0, 'Nenkoff, Mr. Christo', 0, 3, 224),
 ('PP 4348', 9.35, None, 'S', 0, 'Berglund, Mr. Karl Ivar Sven', 0, 3, 226),
 ('SW/PP 751', 10.5, None, 'S', 1, 'Mellors, Mr. William John', 0, 2, 227),
 ('A/5 21173', 7.25, None, 'S', 0, 'Lovell, Mr. John Hall ("Henry")', 0, 3, 228),
 ('236171', 13.0, None, 'S', 0, 'Fahlstrom, Mr. Arne Jonas', 0, 2, 229),
 ('4133', 25.4667, None, 'S', 0, 'Lefebre, Miss. Mathilde', 3, 3, 230),
 ('347067', 7.775, None, 'S', 0, 'Larsson, Mr. Bengt Edvin', 0, 3, 232),
 ('237442', 13.5, None, 'S', 0, 'Sjostedt, Mr. Ernst Adolf', 0, 2, 233),
 ('347077', 31.3875, None, 'S', 1, 'Asplund, Miss. Lillian Gertrud', 4, 3, 234),
 ('C.A. 29566', 10.5, None, 'S', 0, 'Leyson, Mr. Robert William Norman', 0, 2, 235),
 ('W./C. 6609', 7.55, None, 'S', 0, 'Harknett, Miss. Alice Phoebe', 0, 3, 236),
 ('26707', 26.0, None, 'S', 0, 'Hold, Mr. Stephen', 1, 2, 237),
 ('C.A. 31921', 26.25, None, 'S', 1, 'Collyer, Miss. Marjorie "Lottie"', 0, 2, 238),
 ('28665', 10.5, None, 'S', 0, 'Pengelly, Mr. Frederick William', 0, 2, 239),
 ('SCO/W 1585', 12.275, None, 'S', 0, 'Hunt, Mr. George Henry', 0, 2, 240),
 ('2665', 14.4542, None, 'C', 0, 'Zabour, Miss. Thamine', 1, 3, 241),
 ('367230', 15.5, None, 'Q', 1, 'Murphy, Miss. Katherine "Kate"', 1, 3, 242),
 ('W./C. 14263', 10.5, None, 'S', 0, 'Coleridge, Mr. Reginald Charles', 0, 2, 243),
 ('STON/O 2. 3101275', 7.125, None, 'S', 0, 'Maenpaa, Mr. Matti Alexanteri', 0, 3, 244),
 ('2694', 7.225, None, 'C', 0, 'Attalah, Mr. Sleiman', 0, 3, 245),
 ('347071', 7.775, None, 'S', 0, 'Lindahl, Miss. Agda Thorilda Viktoria', 0, 3, 247),
 ('250649', 14.5, None, 'S', 1, 'Hamalainen, Mrs. William (Anna)', 0, 2, 248),
 ('244252', 26.0, None, 'S', 0, 'Carter, Rev. Ernest Courtenay', 1, 2, 250),
 ('362316', 7.25, None, 'S', 0, 'Reed, Mr. James George', 0, 3, 251),
 ('A/5. 3336', 16.1, None, 'S', 0, 'Lobb, Mr. William Arthur', 1, 3, 254),
 ('370129', 20.2125, None, 'S', 0, 'Rosblom, Mrs. Viktor (Helena Wilhelmina)', 0, 3, 255),
 ('2650', 15.2458, None, 'C', 1, 'Touma, Mrs. Darwis (Hanne Youssef Razi)', 0, 3, 256),
 ('PC 17585', 79.2, None, 'C', 1, 'Thorne, Mrs. Gertrude Maybelle', 0, 1, 257),
 ('PC 17755', 512.3292, None, 'C', 1, 'Ward, Miss. Anna', 0, 1, 259),
 ('230433', 26.0, None, 'S', 1, 'Parrish, Mrs. (Lutie Davis)', 0, 2, 260),
 ('384461', 7.75, None, 'Q', 0, 'Smith, Mr. Thomas', 0, 3, 261),
 ('347077', 31.3875, None, 'S', 1, 'Asplund, Master. Edvin Rojj Felix', 4, 3, 262),
 ('382649', 7.75, None, 'Q', 0, 'Henry, Miss. Delia', 0, 3, 265),
 ('C.A. 17248', 10.5, None, 'S', 0, 'Reeves, Mr. David', 0, 2, 266),
 ('3101295', 39.6875, None, 'S', 0, 'Panula, Mr. Ernesti Arvid', 4, 3, 267),
 ('347083', 7.775, None, 'S', 1, 'Persson, Mr. Ernst Ulrik', 1, 3, 268),
 ('113798', 31.0, None, 'S', 0, 'Cairns, Mr. Alexander', 0, 1, 271),
 ('LINE', 0.0, None, 'S', 1, 'Tornquist, Mr. William Henry', 0, 3, 272),
 ('250644', 19.5, None, 'S', 1, 'Mellinger, Mrs. (Elizabeth Anne Maidment)', 0, 2, 273),
 ('370375', 7.75, None, 'Q', 1, 'Healy, Miss. Hanora "Nora"', 0, 3, 275),
 ('347073', 7.75, None, 'S', 0, 'Lindblom, Miss. Augusta Charlotta', 0, 3, 277),
 ('239853', 0.0, None, 'S', 0, 'Parkes, Mr. Francis "Frank"', 0, 2, 278),
 ('382652', 29.125, None, 'Q', 0, 'Rice, Master. Eric', 4, 3, 279),
 ('C.A. 2673', 20.25, None, 'S', 1, 'Abbott, Mrs. Stanton (Rosa Hunt)', 1, 3, 280),
 ('336439', 7.75, None, 'Q', 0, 'Duane, Mr. Frank', 0, 3, 281),
 ('347464', 7.8542, None, 'S', 0, 'Olsson, Mr. Nils Johan Goransson', 0, 3, 282),
 ('345778', 9.5, None, 'S', 0, 'de Pelsmaeker, Mr. Alfons', 0, 3, 283),
 ('A/5. 10482', 8.05, None, 'S', 1, 'Dorking, Mr. Edward Arthur', 0, 3, 284),
 ('349239', 8.6625, None, 'C', 0, 'Stankovic, Mr. Ivan', 0, 3, 286),
 ('345774', 9.5, None, 'S', 1, 'de Mulder, Mr. Theodore', 0, 3, 287),
 ('349206', 7.8958, None, 'S', 0, 'Naidenoff, Mr. Penko', 0, 3, 288),
 ('237798', 13.0, None, 'S', 1, 'Hosono, Mr. Masabumi', 0, 2, 289),
 ('370373', 7.75, None, 'Q', 1, 'Connolly, Miss. Kate', 0, 3, 290),
 ('19877', 78.85, None, 'S', 1, 'Barber, Miss. Ellen "Nellie"', 0, 1, 291),
 ('349236', 8.85, None, 'S', 0, 'Haas, Miss. Aloisia', 0, 3, 294),
 ('349233', 7.8958, None, 'S', 0, 'Mineff, Mr. Ivan', 0, 3, 295),
 ('PC 17612', 27.7208, None, 'C', 0, 'Lewy, Mr. Ervin G', 0, 1, 296),
 ('2693', 7.2292, None, 'C', 0, 'Hanna, Mr. Mansour', 0, 3, 297),
 ('9234', 7.75, None, 'Q', 1, 'Kelly, Miss. Anna Katherine "Annie Kate"', 0, 3, 301),
 ('367226', 23.25, None, 'Q', 1, 'McCoy, Mr. Bernard', 2, 3, 302),
 ('LINE', 0.0, None, 'S', 0, 'Johnson, Mr. William Cahoone Jr', 0, 3, 303),
 ('A/5 2466', 8.05, None, 'S', 0, 'Williams, Mr. Howard Hugh "Harry"', 0, 3, 305),
 ('17421', 110.8833, None, 'C', 1, 'Fleming, Miss. Margaret', 0, 1, 307),
 ('P/PP 3381', 24.0, None, 'C', 0, 'Abelson, Mr. Samuel', 1, 2, 309),
 ('250651', 26.0, None, 'S', 0, 'Lahtinen, Mrs. William (Anna Sylfven)', 1, 2, 313),
 ('349243', 7.8958, None, 'S', 0, 'Hendekovic, Mr. Ignjac', 0, 3, 314),
 ('F.C.C. 13529', 26.25, None, 'S', 0, 'Hart, Mr. Benjamin', 1, 2, 315),
 ('347470', 7.8542, None, 'S', 1, 'Nilsson, Miss. Helmina Josefina', 0, 3, 316),
 ('244367', 26.0, None, 'S', 1, 'Kantor, Mrs. Sinai (Miriam Sternin)', 1, 2, 317),
 ('29011', 14.0, None, 'S', 0, 'Moraweck, Dr. Ernest', 0, 2, 318),
 ('A/5 21172', 7.25, None, 'S', 0, 'Dennis, Mr. Samuel', 0, 3, 321),
 ('349219', 7.8958, None, 'S', 0, 'Danoff, Mr. Yoto', 0, 3, 322),
 ('234818', 12.35, None, 'Q', 1, 'Slayter, Miss. Hilda Mary', 0, 2, 323),
 ('248738', 29.0, None, 'S', 1, 'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)', 1, 2, 324),
 ('CA. 2343', 69.55, None, 'S', 0, 'Sage, Mr. George John Jr', 8, 3, 325),
 ('345364', 6.2375, None, 'S', 0, 'Nysveen, Mr. Johan Hansen', 0, 3, 327),
 ('363291', 20.525, None, 'S', 1, 'Goldsmith, Mrs. Frank John (Emily Alice Brown)', 1, 3, 329),
 ('367226', 23.25, None, 'Q', 1, 'McCoy, Miss. Agnes', 2, 3, 331),
 ('345764', 18.0, None, 'S', 0, 'Vander Planke, Mr. Leo Edmondus', 2, 3, 334),
 ('PC 17611', 133.65, None, 'S', 1, 'Frauenthal, Mrs. Henry William (Clara Heinsheimer)', 1, 1, 335),
 ('349225', 7.8958, None, 'S', 0, 'Denkoff, Mr. Mitto', 0, 3, 336),
 ('7598', 8.05, None, 'S', 1, 'Dahl, Mr. Karl Edwart', 0, 3, 339),
 ('248740', 13.0, None, 'S', 0, 'Collander, Mr. Erik Gustaf', 0, 2, 343),

In [146]:
%%sql
SELECT Name FROM Embarquement
where embarked='C';

 * postgresql://oceane:***@localhost/postgres
168 rows affected.

[('Cumings, Mrs. John Bradley (Florence Briggs Thayer)',),
 ('Nasser, Mrs. Nicholas (Adele Achem)',),
 ('Masselmani, Mrs. Fatima',),
 ('Emir, Mr. Farred Chehab',),
 ('Uruchurtu, Don. Manuel E',),
 ('Spencer, Mrs. William Augustus (Marie Eugenie)',),
 ('Meyer, Mr. Edgar Joseph',),
 ('Mamee, Mr. Hanna',),
 ('Nicola-Yarred, Miss. Jamila',),
 ('Kraeff, Mr. Theodor',),
 ('Laroche, Miss. Simonne Marie Anne Andree',),
 ('Samaan, Mr. Youssef',),
 ('Harper, Mrs. Henry Sleeper (Myna Haxtun)',),
 ('Ostby, Mr. Engelhart Cornelius',),
 ('Novel, Mr. Mansouer',),
 ('Sirayanian, Mr. Orsen',),
 ('Stewart, Mr. Albert A',),
 ('Moubarek, Master. Gerios',),
 ('Chronopoulos, Mr. Apostolos',),
 ('Goldschmidt, Mr. George B',),
 ('Greenfield, Mr. William Bertram',),
 ('Zabour, Miss. Hileni',),
 ('Attalah, Miss. Malake',),
 ('Baxter, Mr. Quigg Edmond',),
 ('Nasser, Mr. Nicholas',),
 ('Nicola-Yarred, Master. Elias',),
 ('Peter, Miss. Anna',),
 ('Drazenoic, Mr. Jozef',),
 ('Richard, Mr. Emile',),
 ('Giglio, Mr. Victor',),
 ('Boulos, Mrs. Joseph (Sultana)',),
 ('Williams, Mr. Charles Duane',),
 ('Smith, Mr. James Clinch',),
 ('Isham, Miss. Ann Elizabeth',),
 ('Pernot, Mr. Rene',),
 ('Brown, Mrs. James Joseph (Margaret Tobin)',),
 ('Lurette, Miss. Elise',),
 ('Youseff, Mr. Gerious',),
 ('Albimona, Mr. Nassef Cassem',),
 ('Blank, Mr. Henry',),
 ('Newell, Miss. Madeleine',),
 ('Bazzani, Miss. Albina',),
 ('Zabour, Miss. Thamine',),
 ('Attalah, Mr. Sleiman',),
 ('Touma, Mrs. Darwis (Hanne Youssef Razi)',),
 ('Thorne, Mrs. Gertrude Maybelle',),
 ('Ward, Miss. Anna',),
 ('Natsch, Mr. Charles H',),
 ('Stankovic, Mr. Ivan',),
 ('Bishop, Mrs. Dickinson H (Helen Walton)',),
 ('Levy, Mr. Rene Jacques',),
 ('Lewy, Mr. Ervin G',),
 ('Hanna, Mr. Mansour',),
 ('Baxter, Mrs. James (Helene DeLaudeniere Chaput)',),
 ('Fleming, Miss. Margaret',),
 ('Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',),
 ('Abelson, Mr. Samuel',),
 ('Francatelli, Miss. Laura Mabel',),
 ('Hays, Miss. Margaret Bechstein',),
 ('Ryerson, Miss. Emily Borie',),
 ('Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',),
 ('Young, Miss. Marie Grice',),
 ('Hippach, Miss. Jean Gertrude',),
 ('Burns, Miss. Elizabeth Margaret',),
 ('Elias, Mr. Tannous',),
 ('Yousif, Mr. Wazli',),
 ('del Carlo, Mr. Sebastiano',),
 ('Barbara, Mrs. (Catherine David)',),
 ('Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',),
 ('Moussa, Mrs. (Mantoura Boulos)',),
 ('Aubart, Mme. Leontine Pauline',),
 ('Harder, Mr. George Achilles',),
 ('Ringhini, Mr. Sante',),
 ('Meyer, Mrs. Edgar Joseph (Leila Saks)',),
 ('Widener, Mr. Harry Elkins',),
 ('Betros, Mr. Tannous',),
 ('Bidois, Miss. Rosalie',),
 ('Nakid, Miss. Maria ("Mary")',),
 ('Lehmann, Miss. Bertha',),
 ('Newell, Miss. Marjorie',),
 ('Gheorgheff, Mr. Stanio',),
 ('Baclini, Miss. Marie Catherine',),
 ('Foreman, Mr. Benjamin Laventall',),
 ('Goldenberg, Mr. Samuel L',),
 ('Jalsevac, Mr. Ivan',),
 ('Baclini, Miss. Helene Barbara',),
 ('Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',),
 ('Bishop, Mr. Dickinson H',),
 ('Kent, Mr. Edward Austin',),
 ('Artagaveytia, Mr. Ramon',),
 ('Yousseff, Mr. Gerious',),
 ('Eustis, Miss. Elizabeth Mussey',),
 ('Penasco y Castellana, Mr. Victor de Satode',),
 ('Rothschild, Mrs. Martin (Elizabeth L. Barrett)',),
 ('Lahoud, Mr. Sarkis',),
 ('Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',),
 ('Kassem, Mr. Fared',),
 ('Toufik, Mr. Nakli',),
 ('Elias, Mr. Joseph Jr',),
 ('Peter, Mrs. Catherine (Catherine Rizk)',),
 ('LeRoy, Miss. Bertha',),
 ('Frolicher, Miss. Hedwig Margaritha',),
 ('Douglas, Mr. Walter Donald',),
 ('Padro y Manent, Mr. Julian',),
 ('Thayer, Mr. John Borland Jr',),
 ('Leeni, Mr. Fahim ("Philip Zenni")',),
 ('Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',),
 ('Robbins, Mr. Victor',),
 ('Doharr, Mr. Tannous',),
 ('Caram, Mrs. Joseph (Maria Elias)',),
 ('Thayer, Mrs. John Borland (Marian Longstreth Morris)',),
 ('Ross, Mr. John Hugo',),
 ('Paulner, Mr. Uscher',),
 ('Frolicher-Stehli, Mr. Maxmillian',),
 ('Stephenson, Mrs. Walter Bertram (Martha Eustis)',),
 ('Boulos, Mr. Hanna',),
 ('Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',),
 ('Homer, Mr. Harry ("Mr E Haven")',),
 ('Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',),
 ('Yasbeck, Mr. Antoni',),
 ('Nakid, Mr. Sahid',),
 ('Stahelin-Maeglin, Dr. Max',),
 ('Sagesser, Mlle. Emma',),
 ('Baclini, Miss. Eugenie',),
 ('Harper, Mr. Henry Sleeper',),
 ('Simonius-Blumer, Col. Oberst Alfons',),
 ('Newell, Mr. Arthur Webster',),
 ('Badt, Mr. Mohamed',),
 ('Cardeza, Mr. Thomas Drake Martinez',),
 ('Hassab, Mr. Hammad',),
 ('Laroche, Mr. Joseph Philippe Lemercier',),
 ('Karun, Miss. Manca',),
 ('Saad, Mr. Khalil',),
 ('Thayer, Mr. John Borland',),
 ('Astor, Mrs. John Jacob (Madeleine Talmadge Force)',),
 ('Barbara, Miss. Saiide',),
 ('Moubarek, Master. Halim Gonios ("William George")',),
 ('Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")',),
 ('Endres, Miss. Caroline Louise',),
 ('Hassan, Mr. Houssein G N',),
 ('Lesurer, Mr. Gustave J',),
 ('Ryerson, Miss. Susan Parker "Suzette"',),
 ('Barah, Mr. Hanna Assi',),
 ('Brewe, Dr. Arthur Jackson',),
 ('Elias, Mr. Dibo',),
 ('Ayoub, Miss. Banoura',),
 ('Guggenheim, Mr. Benjamin',),
 ('Hoyt, Mr. William Fisher',),
 ('Ibrahim Shawah, Mr. Yousseff',),
 ('Thomas, Master. Assad Alexander',),
 ('Mallet, Mr. Albert',),
 ('Mallet, Master. Andre',),
 ('Yasbeck, Mrs. Antoni (Selini Alexander)',),
 ('Saad, Mr. Amin',),
 ('Compton, Miss. Sara Rebecca',),
 ('Marechal, Mr. Pierre',),
 ('Serepeca, Miss. Augusta',),
 ('Lemberopolous, Mr. Peter L',),
 ('Markoff, Mr. Marin',),
 ('Goldenberg, Mrs. Samuel L (Edwiga Grabowska)',),
 ('Boulos, Miss. Nourelain',),
 ('Baclini, Mrs. Solomon (Latifa Qurban)',),
 ('Razi, Mr. Raihed',),
 ('Duran y More, Miss. Asuncion',),
 ('Abelson, Mrs. Samuel (Hannah Wizosky)',),
 ('Najib, Miss. Adele Kiamie "Jane"',),
 ('Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)',),
 ('Behr, Mr. Karl Howell',)]

## requete sql ##

requete 1

In [42]:
#Nous utilisons ici la fonction count afin qu'on puisse compter le nombre de classe . 
#De surcroit , nous ajoutons la clause distinct qui permet d'eviter les doublons.

In [147]:
%%sql
SELECT COUNT(DISTINCT pclass ) from embarquement;

 * postgresql://oceane:***@localhost/postgres
1 rows affected.

[(3,)]

requete 2

In [44]:
#La fonction count nous permet de compter les différents informations par classe
#Le GROUP BY est utile ici car il permet de regrouper les sous-ensembles appartenant à un seul tuple

In [148]:
%%sql

Select pclass , COUNT(distinct PassagerId) from passagers GROUP BY pclass;

 * postgresql://oceane:***@localhost/postgres
3 rows affected.

[(1, 216), (2, 184), (3, 491)]

requete 3

In [46]:
# Utilisation du count 
#Utilisation du GROUP BY

In [213]:
%%sql 
select pclass , sex,  COUNT (*) from passagers where sex='male' or sex='female' GROUP BY pclass ,sex;

 * postgresql://oceane:***@localhost/postgres
6 rows affected.

[(1, 'female', 94),
 (1, 'male', 122),
 (2, 'male', 108),
 (2, 'female', 76),
 (3, 'female', 144),
 (3, 'male', 347)]

In [48]:
# Nous utilisons ici la fonction qui permet de compter dans un attributs les différentes caractéristiques qu'on lui 
#passe en paramètre. Vu que nous cherchons les passagers ayant survecu = 1 et les passagers n'ayant pas survécu = 0
# Pour calculer le pourcentage nous avons multiplé par 100 pour faire un pourcentage.

In [48]:
# Nous utilisons ici la fonction qui permet de compter dans un attributs les différentes caractéristiques qu'on lui 
#passe en paramètre. Vu que nous cherchons les passagers ayant survecu = 1 et les passagers n'ayant pas survécu = 0
# Pour calculer le pourcentage nous avons multiplé par 100 pour faire un pourcentage.

Requete 4

In [150]:
%%sql 
select survived , COUNT(*) from passagers where survived ='0' or survived ='1' GROUP BY survived;

 * postgresql://oceane:***@localhost/postgres
2 rows affected.

[(0, 549), (1, 342)]

In [151]:
%%sql

select survived , (100 * COUNT(*))  / (select COUNT(*) from passagers) as pourcentage
from passagers 

group by survived ;

 * postgresql://oceane:***@localhost/postgres
2 rows affected.

[(0, 61), (1, 38)]

In [ ]:
#Nous avons crée une vues pour avoir une version simplifié de la table .

requete 5

In [194]:
%%sql

Create view survivant as 
select  survived , pclass , COUNT(*)
from passagers 
where survived ='0' or survived ='1' 
GROUP BY  survived , pclass;

 * postgresql://oceane:***@localhost/postgres
(psycopg2.errors.DuplicateTable) relation "survivant" already exists

[SQL: Create view survivant as
select  survived , pclass , COUNT(*)
from passagers
where survived ='0' or survived ='1'
GROUP BY  survived , pclass;]
(Background on this error at: http://sqlalche.me/e/14/f405)

In [195]:
%%sql

select* from survivant;

 * postgresql://oceane:***@localhost/postgres
6 rows affected.

[(0, 3, 372), (0, 1, 80), (0, 2, 97), (1, 3, 119), (1, 2, 87), (1, 1, 136)]

In [ ]:
#Nous avons crée une vues pour avoir une version simplifié de la table . (table intermédiraire)

requete 6

In [196]:
%%sql

CREATE view SurvivantS as
select survived , sex , COUNT(*) 
from passagers 
where survived ='0' or survived ='1'
GROUP BY survived , sex;

 * postgresql://oceane:***@localhost/postgres
(psycopg2.errors.DuplicateTable) relation "survivants" already exists

[SQL: CREATE view SurvivantS as
select survived , sex , COUNT(*)
from passagers
where survived ='0' or survived ='1'
GROUP BY survived , sex;]
(Background on this error at: http://sqlalche.me/e/14/f405)

In [197]:
%%sql
select * from SurvivantS;

 * postgresql://oceane:***@localhost/postgres
4 rows affected.

[(0, 'female', 81), (1, 'female', 233), (1, 'male', 109), (0, 'male', 468)]